In [161]:
df = pd.read_csv("atm_cash_management_dataset.csv") pandas as pd

print("Dataset shape:", df.shape)
df.head()
df = pd.read_csv(

FileNotFoundError: [Errno 2] No such file or directory: 'atm_cash_management_dataset.csv'

In [12]:
df

,ATM_ID,Date,Day_of_Week,Time_of_Day,Total_Withdrawals,Total_Deposits,Location_Type,Holiday_Flag,Special_Event_Flag,Previous_Day_Cash_Level,Weather_Condition,Nearby_Competitor_ATMs,Cash_Demand_Next_Day
0,ATM_0041,2022-04-25,Monday,Morning,57450,9308,Standalone,0,0,112953,Rainy,5,44165
1,ATM_0007,2023-11-24,Friday,Morning,72845,17896,Supermarket,0,0,115348,Clear,0,41249
2,ATM_0014,2022-08-27,Saturday,Morning,42957,12712,Supermarket,0,0,90731,Cloudy,1,29901
3,ATM_0029,2023-08-27,Sunday,Evening,43014,1375,Mall,0,0,88754,Rainy,5,44155
4,ATM_0028,2022-12-15,Thursday,Evening,36379,2938,Bank Branch,0,0,129312,Snowy,0,29784
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5653,ATM_0029,2022-07-02,Saturday,Night,32027,3097,Standalone,0,0,96493,Clear,2,35148
5654,ATM_0050,2023-12-08,Friday,Afternoon,60120,4948,Mall,0,0,128933,Rainy,5,51927
5655,ATM_0036,2022-10-04,Tuesday,Evening,32551,10819,Mall,0,0,104519,Snowy,3,31127
5656,ATM_0010,2022-04-19,Tuesday,Night,52965,13372,Gas Station,0,0,107829,Rainy,2,35886
5657,ATM_0039,2022-07-26,Tuesday,Evening,61754,11348,Mall,0,0,88722,Cloudy,3,52971

In [2]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (5658, 13)

Columns:
['ATM_ID', 'Date', 'Day_of_Week', 'Time_of_Day', 'Total_Withdrawals', 'Total_Deposits', 'Location_Type', 'Holiday_Flag', 'Special_Event_Flag', 'Previous_Day_Cash_Level', 'Weather_Condition', 'Nearby_Competitor_ATMs', 'Cash_Demand_Next_Day']

In [3]:
print("\nData types:")
print(df.dtypes)

Data types:
ATM_ID                       str
Date                         str
Day_of_Week                  str
Time_of_Day                  str
Total_Withdrawals          int64
Total_Deposits             int64
Location_Type                str
Holiday_Flag               int64
Special_Event_Flag         int64
Previous_Day_Cash_Level    int64
Weather_Condition            str
Nearby_Competitor_ATMs     int64
Cash_Demand_Next_Day       int64
dtype: object

In [4]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
ATM_ID                     0
Date                       0
Day_of_Week                0
Time_of_Day                0
Total_Withdrawals          0
Total_Deposits             0
Location_Type              0
Holiday_Flag               0
Special_Event_Flag         0
Previous_Day_Cash_Level    0
Weather_Condition          0
Nearby_Competitor_ATMs     0
Cash_Demand_Next_Day       0
dtype: int64

In [5]:
print("\nDuplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0

In [6]:
print("\nUnique values:")
print(df.nunique())

Unique values:
ATM_ID                       50
Date                        731
Day_of_Week                   7
Time_of_Day                   4
Total_Withdrawals          5347
Total_Deposits             4723
Location_Type                 5
Holiday_Flag                  2
Special_Event_Flag            2
Previous_Day_Cash_Level    5452
Weather_Condition             4
Nearby_Competitor_ATMs        6
Cash_Demand_Next_Day       5363
dtype: int64

In [7]:
print("\nStatistics:")
print(df.describe(include="all"))

Statistics:
          ATM_ID        Date Day_of_Week Time_of_Day  Total_Withdrawals  \
count       5658        5658        5658        5658        5658.000000
unique        50         731           7           4                NaN
top     ATM_0044  2022-11-04      Monday   Afternoon                NaN
freq         152          16         831        1449                NaN
mean         NaN         NaN         NaN         NaN       49808.106928
std          NaN         NaN         NaN         NaN       14903.539241
min          NaN         NaN         NaN         NaN        1380.000000
25%          NaN         NaN         NaN         NaN       39469.250000
50%          NaN         NaN         NaN         NaN       50039.000000
75%          NaN         NaN         NaN         NaN       60132.500000
max          NaN         NaN         NaN         NaN      107790.000000

        Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
count      5658.000000          5658   5658.000000         5658.000000
unique             NaN             5           NaN                 NaN
top                NaN   Gas Station           NaN                 NaN
freq               NaN          1144           NaN                 NaN
mean      10129.078473           NaN      0.022093            0.096501
std        4878.853583           NaN      0.146998            0.295303
min           0.000000           NaN      0.000000            0.000000
25%        6765.000000           NaN      0.000000            0.000000
50%       10048.000000           NaN      0.000000            0.000000
75%       13430.000000           NaN      0.000000            0.000000
max       32395.000000           NaN      1.000000            1.000000

        Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
count               5658.000000              5658             5658.000000
unique                      NaN                 4                     NaN
top                         NaN             Clear                     NaN
freq                        NaN              1469                     NaN
mean              100283.994698               NaN                2.477731
std                20122.365608               NaN                1.719487
min                23266.000000               NaN                0.000000
25%                86533.500000               NaN                1.000000
50%               100276.500000               NaN                2.000000
75%               113956.500000               NaN                4.000000
max               172227.000000               NaN                5.000000

        Cash_Demand_Next_Day
count            5658.000000
unique                   NaN
top                      NaN
freq                     NaN
mean            43085.207494
std             16797.100086
min                 0.000000
25%             31558.750000
50%             42589.500000
75%             53831.000000
max            114724.000000

In [10]:
df["Date"] = pd.to_datetime(df["Date"])

In [11]:
print(df["Date"].dtype)
print(df["Date"].min())
print(df["Date"].max())

datetime64[us]
2022-01-01 00:00:00
2024-01-01 00:00:00

In [13]:
records_per_atm = df.groupby("ATM_ID")["Date"].agg(
    ["min", "max", "count"]
)

print(records_per_atm)

                min        max  count
ATM_ID
ATM_0001 2022-01-05 2023-12-16    120
ATM_0002 2022-01-05 2024-01-01    117
ATM_0003 2022-01-01 2023-12-22    111
ATM_0004 2022-01-03 2024-01-01    101
ATM_0005 2022-01-10 2023-12-25     90
ATM_0006 2022-01-08 2023-12-30    129
ATM_0007 2022-01-02 2023-12-25    125
ATM_0008 2022-01-01 2024-01-01    117
ATM_0009 2022-01-09 2023-12-30    123
ATM_0010 2022-01-13 2023-12-27    116
ATM_0011 2022-01-02 2023-12-28    109
ATM_0012 2022-01-01 2023-12-30    118
ATM_0013 2022-01-02 2023-12-30    123
ATM_0014 2022-01-05 2023-12-24     99
ATM_0015 2022-01-04 2024-01-01    108
ATM_0016 2022-01-05 2024-01-01    107
ATM_0017 2022-01-04 2023-12-25    106
ATM_0018 2022-01-01 2023-12-29    119
ATM_0019 2022-01-12 2023-12-30    108
ATM_0020 2022-01-15 2023-12-28    124
ATM_0021 2022-01-11 2023-12-30    116
ATM_0022 2022-01-09 2023-12-28    115
ATM_0023 2022-01-07 2023-12-30    111
ATM_0024 2022-01-09 2024-01-01    115
ATM_0025 2022-01-03 2023-12-22    107
ATM_0026 2022-01-03 2023-12-17    126
ATM_0027 2022-01-04 2023-12-31    109
ATM_0028 2022-01-19 2023-12-29    122
ATM_0029 2022-01-04 2024-01-01     98
ATM_0030 2022-01-04 2023-12-28    106
ATM_0031 2022-01-10 2023-12-31    124
ATM_0032 2022-01-08 2023-12-26     93
ATM_0033 2022-01-08 2023-12-26    106
ATM_0034 2022-01-08 2023-12-08    100
ATM_0035 2022-01-02 2023-12-27    113
ATM_0036 2022-01-08 2023-12-16    118
ATM_0037 2022-01-01 2023-12-29    133
ATM_0038 2022-01-09 2023-12-31    107
ATM_0039 2022-01-09 2024-01-01    118
ATM_0040 2022-01-08 2023-12-26    112
ATM_0041 2022-01-03 2023-12-23    100
ATM_0042 2022-01-01 2023-12-29    103
ATM_0043 2022-01-01 2023-12-29    120
ATM_0044 2022-01-05 2023-12-28    152
ATM_0045 2022-01-09 2023-12-30    105
ATM_0046 2022-01-02 2023-12-18    115
ATM_0047 2022-01-20 2024-01-01    124
ATM_0048 2022-01-04 2023-12-30    110
ATM_0049 2022-01-10 2023-12-28    109
ATM_0050 2022-01-21 2023-12-30    101

In [14]:
print(df.groupby("ATM_ID")["Date"].nunique().describe())

count     50.000000
mean     104.460000
std        9.721027
min       81.000000
25%       97.250000
50%      105.000000
75%      110.750000
max      136.000000
Name: Date, dtype: float64

In [15]:
df["Date"] = pd.to_datetime(df["Date"])

df["Days_Since_Previous"] = (
    df.groupby("ATM_ID")["Date"]
      .diff()
      .dt.days
)

print(df["Days_Since_Previous"].describe())

count    5608.000000
mean       -0.142475
std       298.785680
min      -719.000000
25%      -214.000000
50%         2.000000
75%       210.000000
max       724.000000
Name: Days_Since_Previous, dtype: float64

In [16]:
print(
    df["Days_Since_Previous"]
    .value_counts()
    .sort_index()
    .head(20)
)

Days_Since_Previous
-719.0    1
-715.0    1
-710.0    1
-708.0    2
-706.0    2
-703.0    2
-698.0    1
-696.0    1
-692.0    1
-691.0    1
-690.0    1
-685.0    1
-679.0    1
-678.0    1
-677.0    1
-675.0    1
-674.0    1
-669.0    3
-668.0    1
-666.0    4
Name: count, dtype: int64

In [18]:
df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values(
    ["ATM_ID", "Date"]
).reset_index(drop=True)

In [19]:
df["Days_Since_Previous"] = (
    df.groupby("ATM_ID")["Date"]
      .diff()
      .dt.days
)

In [20]:
print(df["Days_Since_Previous"].describe())

count    5608.000000
mean        6.417439
std         6.352885
min         0.000000
25%         2.000000
50%         4.000000
75%         9.000000
max        52.000000
Name: Days_Since_Previous, dtype: float64

In [21]:
print(
    df["Days_Since_Previous"]
      .value_counts()
      .sort_index()
      .head(20)
)

Days_Since_Previous
0.0     435
1.0     802
2.0     575
3.0     535
4.0     473
5.0     378
6.0     336
7.0     307
8.0     249
9.0     213
10.0    185
11.0    162
12.0    146
13.0    126
14.0    103
15.0     76
16.0     64
17.0     62
18.0     56
19.0     40
Name: count, dtype: int64

In [22]:
same_day = df[df["Days_Since_Previous"] == 0]

print(same_day[
    ["ATM_ID", "Date", "Time_of_Day"]
].head(30))

       ATM_ID       Date Time_of_Day
8    ATM_0001 2022-03-05     Morning
25   ATM_0001 2022-05-27     Morning
38   ATM_0001 2022-07-28   Afternoon
47   ATM_0001 2022-10-16   Afternoon
52   ATM_0001 2022-11-06       Night
53   ATM_0001 2022-11-06       Night
58   ATM_0001 2022-11-23       Night
61   ATM_0001 2022-11-30     Evening
88   ATM_0001 2023-07-03       Night
125  ATM_0002 2022-02-03     Morning
138  ATM_0002 2022-05-24       Night
155  ATM_0002 2022-09-17     Evening
169  ATM_0002 2022-12-19       Night
173  ATM_0002 2023-01-05     Evening
181  ATM_0002 2023-02-19       Night
186  ATM_0002 2023-03-27   Afternoon
193  ATM_0002 2023-05-10   Afternoon
210  ATM_0002 2023-07-07     Evening
231  ATM_0002 2023-11-25   Afternoon
241  ATM_0003 2022-01-30   Afternoon
244  ATM_0003 2022-02-01     Morning
255  ATM_0003 2022-04-18       Night
259  ATM_0003 2022-05-24   Afternoon
284  ATM_0003 2022-10-25     Evening
288  ATM_0003 2022-11-06     Evening
295  ATM_0003 2022-12-05     Morning
322  ATM_0003 2023-05-25     Morning
324  ATM_0003 2023-06-04       Night
326  ATM_0003 2023-06-10       Night
346  ATM_0003 2023-12-14   Afternoon

In [23]:
print(
    df[df["Days_Since_Previous"] == 0]
    .groupby(["ATM_ID", "Date"])
    .size()
    .value_counts()
)

1    392
2     20
3      1
Name: count, dtype: int64

In [24]:
repeated = (
    df.groupby(["ATM_ID", "Date"])
      .size()
      .reset_index(name="Count")
)

repeated = repeated[repeated["Count"] > 1]

print(repeated)

        ATM_ID       Date  Count
7     ATM_0001 2022-03-05      2
23    ATM_0001 2022-05-27      2
35    ATM_0001 2022-07-28      2
43    ATM_0001 2022-10-16      2
47    ATM_0001 2022-11-06      3
...        ...        ...    ...
5184  ATM_0050 2023-02-17      2
5192  ATM_0050 2023-04-17      2
5200  ATM_0050 2023-06-14      2
5201  ATM_0050 2023-06-28      2
5203  ATM_0050 2023-07-07      2

[413 rows x 3 columns]

In [25]:
for _, row in repeated.iterrows():
    print("\n", row["ATM_ID"], row["Date"])
    print(
        df[
            (df["ATM_ID"] == row["ATM_ID"]) &
            (df["Date"] == row["Date"])
        ]
    )

 ATM_0001 2022-03-05 00:00:00
     ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
7  ATM_0001 2022-03-05    Saturday   Afternoon              63303
8  ATM_0001 2022-03-05    Saturday     Morning              61950

   Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
7            7896   Bank Branch             0                   0
8           13590    Standalone             0                   1

   Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
7                    47915            Cloudy                       2
8                   110780             Rainy                       4

   Cash_Demand_Next_Day  Days_Since_Previous
7                 63926                  6.0
8                 62604                  0.0

 ATM_0001 2022-05-27 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
24  ATM_0001 2022-05-27      Friday     Evening              48292
25  ATM_0001 2022-05-27      Friday     Morning              26192

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
24            7581   Supermarket             0                   0
25            8963   Bank Branch             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
24                    95065             Clear                       3
25                   112470             Snowy                       0

    Cash_Demand_Next_Day  Days_Since_Previous
24                 51500                  3.0
25                 16555                  0.0

 ATM_0001 2022-07-28 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
37  ATM_0001 2022-07-28    Thursday     Morning              33132
38  ATM_0001 2022-07-28    Thursday   Afternoon              62470

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
37           10405          Mall             0                   0
38           10503    Standalone             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
37                    83011             Rainy                       0
38                   110282             Clear                       2

    Cash_Demand_Next_Day  Days_Since_Previous
37                 23842                 12.0
38                 50263                  0.0

 ATM_0001 2022-10-16 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
46  ATM_0001 2022-10-16      Sunday     Evening              75645
47  ATM_0001 2022-10-16      Sunday   Afternoon              71705

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
46           16049   Gas Station             0                   0
47           16359   Bank Branch             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
46                   108793            Cloudy                       2
47                    74836            Cloudy                       2

    Cash_Demand_Next_Day  Days_Since_Previous
46                 72789                 10.0
47                 66029                  0.0

 ATM_0001 2022-11-06 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
51  ATM_0001 2022-11-06      Sunday     Morning              69652
52  ATM_0001 2022-11-06      Sunday       Night              77276
53  ATM_0001 2022-11-06      Sunday       Night              28044

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
51           14322   Supermarket             0                   0
52            7579   Gas Station             0                   0
53           12472   Gas Station             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
51                    56746             Snowy                       1
52                   116095            Cloudy                       5
53                    72323             Clear                       5

    Cash_Demand_Next_Day  Days_Since_Previous
51                 60113                  2.0
52                 78121                  0.0
53                 11500                  0.0

 ATM_0001 2022-11-23 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
57  ATM_0001 2022-11-23   Wednesday     Morning              59320
58  ATM_0001 2022-11-23   Wednesday       Night              40834

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
57            3817    Standalone             0                   0
58           13981   Gas Station             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
57                   125488             Snowy                       1
58                    99967             Clear                       3

    Cash_Demand_Next_Day  Days_Since_Previous
57                 61732                  4.0
58                 22040                  0.0

 ATM_0001 2022-11-30 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
60  ATM_0001 2022-11-30   Wednesday     Morning              55787
61  ATM_0001 2022-11-30   Wednesday     Evening              51694

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
60            2978          Mall             0                   0
61            5339          Mall             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
60                    88325             Snowy                       3
61                    80690             Snowy                       4

    Cash_Demand_Next_Day  Days_Since_Previous
60                 43793                  2.0
61                 48197                  0.0

 ATM_0001 2023-07-03 00:00:00
      ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
87  ATM_0001 2023-07-03      Monday     Evening              56774
88  ATM_0001 2023-07-03      Monday       Night              43341

    Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
87            8200   Gas Station             0                   0
88           10167   Bank Branch             0                   0

    Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
87                   108242             Rainy                       4
88                    73939             Clear                       5

    Cash_Demand_Next_Day  Days_Since_Previous
87                 48417                  2.0
88                 38527                  0.0

 ATM_0002 2022-02-03 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
124  ATM_0002 2022-02-03    Thursday     Evening              50132
125  ATM_0002 2022-02-03    Thursday     Morning              25447

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
124            2922   Gas Station             0                   0
125           22616          Mall             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
124                   119557             Snowy                       0
125                    88195             Clear                       5

     Cash_Demand_Next_Day  Days_Since_Previous
124                 57954                 15.0
125                 11178                  0.0

 ATM_0002 2022-05-24 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
137  ATM_0002 2022-05-24     Tuesday     Morning              43798
138  ATM_0002 2022-05-24     Tuesday       Night              38998

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
137           14694    Standalone             0                   1
138            5550   Gas Station             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
137                    69404             Snowy                       3
138                    94477             Clear                       3

     Cash_Demand_Next_Day  Days_Since_Previous
137                 42444                  6.0
138                 27514                  0.0

 ATM_0002 2022-09-17 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
154  ATM_0002 2022-09-17    Saturday   Afternoon              46837
155  ATM_0002 2022-09-17    Saturday     Evening              47876

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
154           22403   Gas Station             0                   1
155           18853    Standalone             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
154                    90060             Clear                       0
155                    77321             Clear                       3

     Cash_Demand_Next_Day  Days_Since_Previous
154                 31275                  2.0
155                 37636                  0.0

 ATM_0002 2022-12-19 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
168  ATM_0002 2022-12-19      Monday   Afternoon              47529
169  ATM_0002 2022-12-19      Monday       Night              27504

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
168           10422   Gas Station             0                   0
169            9895   Gas Station             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
168                   129772            Cloudy                       0
169                    51595            Cloudy                       0

     Cash_Demand_Next_Day  Days_Since_Previous
168                 34537                  7.0
169                 15678                  0.0

 ATM_0002 2023-01-05 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
172  ATM_0002 2023-01-05    Thursday     Evening              31855
173  ATM_0002 2023-01-05    Thursday     Evening              31760

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
172           18362   Gas Station             0                   0
173            8770   Bank Branch             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
172                   108380             Rainy                       4
173                    86322            Cloudy                       1

     Cash_Demand_Next_Day  Days_Since_Previous
172                 21678                 12.0
173                 30034                  0.0

 ATM_0002 2023-02-19 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
180  ATM_0002 2023-02-19      Sunday       Night              47633
181  ATM_0002 2023-02-19      Sunday       Night              55507

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
180            5719   Bank Branch             0                   1
181            9567    Standalone             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
180                   100711             Snowy                       1
181                   121819             Clear                       2

     Cash_Demand_Next_Day  Days_Since_Previous
180                 59100                  7.0
181                 60862                  0.0

 ATM_0002 2023-03-27 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
185  ATM_0002 2023-03-27      Monday     Morning              34243
186  ATM_0002 2023-03-27      Monday   Afternoon              45356

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
185           14230   Gas Station             0                   0
186            9696   Gas Station             0                   1

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
185                    97930             Snowy                       3
186                    76350             Snowy                       5

     Cash_Demand_Next_Day  Days_Since_Previous
185                 33005                  9.0
186                 48345                  0.0

 ATM_0002 2023-05-10 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
192  ATM_0002 2023-05-10   Wednesday     Morning              47985
193  ATM_0002 2023-05-10   Wednesday   Afternoon              64350

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
192           14054    Standalone             0                   0
193            9888   Bank Branch             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
192                   115869             Clear                       0
193                    86222            Cloudy                       5

     Cash_Demand_Next_Day  Days_Since_Previous
192                 34261                  5.0
193                 67013                  0.0

 ATM_0002 2023-07-07 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
209  ATM_0002 2023-07-07      Friday     Morning              59342
210  ATM_0002 2023-07-07      Friday     Evening              38810

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
209           10601    Standalone             0                   0
210            6692   Bank Branch             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
209                   110288             Clear                       5
210                   115068             Snowy                       5

     Cash_Demand_Next_Day  Days_Since_Previous
209                 44039                  2.0
210                 31402                  0.0

 ATM_0002 2023-11-25 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
230  ATM_0002 2023-11-25    Saturday   Afternoon              16009
231  ATM_0002 2023-11-25    Saturday   Afternoon              59182

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
230            8246   Gas Station             0                   0
231           16015          Mall             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
230                    95445             Clear                       2
231                   123606            Cloudy                       0

     Cash_Demand_Next_Day  Days_Since_Previous
230                  9494                  6.0
231                 52710                  0.0

 ATM_0003 2022-01-30 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
240  ATM_0003 2022-01-30      Sunday     Morning              17706
241  ATM_0003 2022-01-30      Sunday   Afternoon              38734

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
240            9969          Mall             0                   1
241           14477   Gas Station             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
240                   116769             Snowy                       5
241                   116744             Rainy                       4

     Cash_Demand_Next_Day  Days_Since_Previous
240                 18963                  6.0
241                 34361                  0.0

 ATM_0003 2022-02-01 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
243  ATM_0003 2022-02-01     Tuesday   Afternoon              26988
244  ATM_0003 2022-02-01     Tuesday     Morning              33938

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
243           16388   Bank Branch             0                   0
244           14830   Bank Branch             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
243                   106646             Rainy                       1
244                   111205             Clear                       0

     Cash_Demand_Next_Day  Days_Since_Previous
243                 12684                  1.0
244                 16360                  0.0

 ATM_0003 2022-04-18 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
254  ATM_0003 2022-04-18      Monday       Night              38791
255  ATM_0003 2022-04-18      Monday       Night              42526

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
254            5768    Standalone             0                   0
255           15050          Mall             0                   1

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
254                   124732             Rainy                       2
255                    68322            Cloudy                       4

     Cash_Demand_Next_Day  Days_Since_Previous
254                 33556                 11.0
255                 30219                  0.0

 ATM_0003 2022-05-24 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
258  ATM_0003 2022-05-24     Tuesday     Morning              50033
259  ATM_0003 2022-05-24     Tuesday   Afternoon              67777

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
258            8626    Standalone             0                   0
259           14491   Supermarket             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
258                    90855             Clear                       2
259                    86124             Snowy                       1

     Cash_Demand_Next_Day  Days_Since_Previous
258                 39133                 12.0
259                 62756                  0.0

 ATM_0003 2022-10-25 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
283  ATM_0003 2022-10-25     Tuesday   Afternoon              54645
284  ATM_0003 2022-10-25     Tuesday     Evening              30990

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
283           12378   Bank Branch             0                   0
284           11993   Gas Station             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
283                   111792             Clear                       5
284                    92599             Rainy                       0

     Cash_Demand_Next_Day  Days_Since_Previous
283                 41029                  3.0
284                 19013                  0.0

 ATM_0003 2022-11-06 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
287  ATM_0003 2022-11-06      Sunday   Afternoon              57501
288  ATM_0003 2022-11-06      Sunday     Evening              67251

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
287           12497   Bank Branch             0                   0
288            2698          Mall             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \
287                   117688            Cloudy                       1
288                    85856             Clear                       3

     Cash_Demand_Next_Day  Days_Since_Previous
287                 54777                  4.0
288                 75956                  0.0

 ATM_0003 2022-12-05 00:00:00
       ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  \
294  ATM_0003 2022-12-05      Monday     Morning              54844
295  ATM_0003 2022-12-05      Monday     Morning              80267

     Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  \
294            9694   Bank Branch             0                   0
295           12458   Supermarket             0                   0

     Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  \

In [26]:
repeated = (
    df.groupby(["ATM_ID", "Date"])
      .size()
      .reset_index(name="Count")
)

repeated = repeated[repeated["Count"] > 1]

print(repeated)

        ATM_ID       Date  Count
7     ATM_0001 2022-03-05      2
23    ATM_0001 2022-05-27      2
35    ATM_0001 2022-07-28      2
43    ATM_0001 2022-10-16      2
47    ATM_0001 2022-11-06      3
...        ...        ...    ...
5184  ATM_0050 2023-02-17      2
5192  ATM_0050 2023-04-17      2
5200  ATM_0050 2023-06-14      2
5201  ATM_0050 2023-06-28      2
5203  ATM_0050 2023-07-07      2

[413 rows x 3 columns]

In [27]:
for _, row in repeated.iterrows():
    print("\n---", row["ATM_ID"], row["Date"], "---")

    print(
        df[
            (df["ATM_ID"] == row["ATM_ID"]) &
            (df["Date"] == row["Date"])
        ].to_string(index=False)
    )

--- ATM_0001 2022-03-05 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-03-05    Saturday   Afternoon              63303            7896   Bank Branch             0                   0                    47915            Cloudy                       2                 63926                  6.0
ATM_0001 2022-03-05    Saturday     Morning              61950           13590    Standalone             0                   1                   110780             Rainy                       4                 62604                  0.0

--- ATM_0001 2022-05-27 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-05-27      Friday     Evening              48292            7581   Supermarket             0                   0                    95065             Clear                       3                 51500                  3.0
ATM_0001 2022-05-27      Friday     Morning              26192            8963   Bank Branch             0                   0                   112470             Snowy                       0                 16555                  0.0

--- ATM_0001 2022-07-28 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-07-28    Thursday     Morning              33132           10405          Mall             0                   0                    83011             Rainy                       0                 23842                 12.0
ATM_0001 2022-07-28    Thursday   Afternoon              62470           10503    Standalone             0                   0                   110282             Clear                       2                 50263                  0.0

--- ATM_0001 2022-10-16 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-10-16      Sunday     Evening              75645           16049   Gas Station             0                   0                   108793            Cloudy                       2                 72789                 10.0
ATM_0001 2022-10-16      Sunday   Afternoon              71705           16359   Bank Branch             0                   0                    74836            Cloudy                       2                 66029                  0.0

--- ATM_0001 2022-11-06 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-11-06      Sunday     Morning              69652           14322   Supermarket             0                   0                    56746             Snowy                       1                 60113                  2.0
ATM_0001 2022-11-06      Sunday       Night              77276            7579   Gas Station             0                   0                   116095            Cloudy                       5                 78121                  0.0
ATM_0001 2022-11-06      Sunday       Night              28044           12472   Gas Station             0                   0                    72323             Clear                       5                 11500                  0.0

--- ATM_0001 2022-11-23 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-11-23   Wednesday     Morning              59320            3817    Standalone             0                   0                   125488             Snowy                       1                 61732                  4.0
ATM_0001 2022-11-23   Wednesday       Night              40834           13981   Gas Station             0                   0                    99967             Clear                       3                 22040                  0.0

--- ATM_0001 2022-11-30 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-11-30   Wednesday     Morning              55787            2978          Mall             0                   0                    88325             Snowy                       3                 43793                  2.0
ATM_0001 2022-11-30   Wednesday     Evening              51694            5339          Mall             0                   0                    80690             Snowy                       4                 48197                  0.0

--- ATM_0001 2023-07-03 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2023-07-03      Monday     Evening              56774            8200   Gas Station             0                   0                   108242             Rainy                       4                 48417                  2.0
ATM_0001 2023-07-03      Monday       Night              43341           10167   Bank Branch             0                   0                    73939             Clear                       5                 38527                  0.0

--- ATM_0002 2022-02-03 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2022-02-03    Thursday     Evening              50132            2922   Gas Station             0                   0                   119557             Snowy                       0                 57954                 15.0
ATM_0002 2022-02-03    Thursday     Morning              25447           22616          Mall             0                   0                    88195             Clear                       5                 11178                  0.0

--- ATM_0002 2022-05-24 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2022-05-24     Tuesday     Morning              43798           14694    Standalone             0                   1                    69404             Snowy                       3                 42444                  6.0
ATM_0002 2022-05-24     Tuesday       Night              38998            5550   Gas Station             0                   0                    94477             Clear                       3                 27514                  0.0

--- ATM_0002 2022-09-17 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2022-09-17    Saturday   Afternoon              46837           22403   Gas Station             0                   1                    90060             Clear                       0                 31275                  2.0
ATM_0002 2022-09-17    Saturday     Evening              47876           18853    Standalone             0                   0                    77321             Clear                       3                 37636                  0.0

--- ATM_0002 2022-12-19 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2022-12-19      Monday   Afternoon              47529           10422   Gas Station             0                   0                   129772            Cloudy                       0                 34537                  7.0
ATM_0002 2022-12-19      Monday       Night              27504            9895   Gas Station             0                   0                    51595            Cloudy                       0                 15678                  0.0

--- ATM_0002 2023-01-05 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-01-05    Thursday     Evening              31855           18362   Gas Station             0                   0                   108380             Rainy                       4                 21678                 12.0
ATM_0002 2023-01-05    Thursday     Evening              31760            8770   Bank Branch             0                   0                    86322            Cloudy                       1                 30034                  0.0

--- ATM_0002 2023-02-19 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-02-19      Sunday       Night              47633            5719   Bank Branch             0                   1                   100711             Snowy                       1                 59100                  7.0
ATM_0002 2023-02-19      Sunday       Night              55507            9567    Standalone             0                   0                   121819             Clear                       2                 60862                  0.0

--- ATM_0002 2023-03-27 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-03-27      Monday     Morning              34243           14230   Gas Station             0                   0                    97930             Snowy                       3                 33005                  9.0
ATM_0002 2023-03-27      Monday   Afternoon              45356            9696   Gas Station             0                   1                    76350             Snowy                       5                 48345                  0.0

--- ATM_0002 2023-05-10 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-05-10   Wednesday     Morning              47985           14054    Standalone             0                   0                   115869             Clear                       0                 34261                  5.0
ATM_0002 2023-05-10   Wednesday   Afternoon              64350            9888   Bank Branch             0                   0                    86222            Cloudy                       5                 67013                  0.0

--- ATM_0002 2023-07-07 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-07-07      Friday     Morning              59342           10601    Standalone             0                   0                   110288             Clear                       5                 44039                  2.0
ATM_0002 2023-07-07      Friday     Evening              38810            6692   Bank Branch             0                   0                   115068             Snowy                       5                 31402                  0.0

--- ATM_0002 2023-11-25 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-11-25    Saturday   Afternoon              16009            8246   Gas Station             0                   0                    95445             Clear                       2                  9494                  6.0
ATM_0002 2023-11-25    Saturday   Afternoon              59182           16015          Mall             0                   0                   123606            Cloudy                       0                 52710                  0.0

--- ATM_0003 2022-01-30 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-01-30      Sunday     Morning              17706            9969          Mall             0                   1                   116769             Snowy                       5                 18963                  6.0
ATM_0003 2022-01-30      Sunday   Afternoon              38734           14477   Gas Station             0                   0                   116744             Rainy                       4                 34361                  0.0

--- ATM_0003 2022-02-01 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-02-01     Tuesday   Afternoon              26988           16388   Bank Branch             0                   0                   106646             Rainy                       1                 12684                  1.0
ATM_0003 2022-02-01     Tuesday     Morning              33938           14830   Bank Branch             0                   0                   111205             Clear                       0                 16360                  0.0

--- ATM_0003 2022-04-18 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-04-18      Monday       Night              38791            5768    Standalone             0                   0                   124732             Rainy                       2                 33556                 11.0
ATM_0003 2022-04-18      Monday       Night              42526           15050          Mall             0                   1                    68322            Cloudy                       4                 30219                  0.0

--- ATM_0003 2022-05-24 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-05-24     Tuesday     Morning              50033            8626    Standalone             0                   0                    90855             Clear                       2                 39133                 12.0
ATM_0003 2022-05-24     Tuesday   Afternoon              67777           14491   Supermarket             0                   0                    86124             Snowy                       1                 62756                  0.0

--- ATM_0003 2022-10-25 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-10-25     Tuesday   Afternoon              54645           12378   Bank Branch             0                   0                   111792             Clear                       5                 41029                  3.0
ATM_0003 2022-10-25     Tuesday     Evening              30990           11993   Gas Station             0                   0                    92599             Rainy                       0                 19013                  0.0

--- ATM_0003 2022-11-06 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-11-06      Sunday   Afternoon              57501           12497   Bank Branch             0                   0                   117688            Cloudy                       1                 54777                  4.0
ATM_0003 2022-11-06      Sunday     Evening              67251            2698          Mall             0                   0                    85856             Clear                       3                 75956                  0.0

--- ATM_0003 2022-12-05 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-12-05      Monday     Morning              54844            9694   Bank Branch             0                   0                   110004            Cloudy                       0                 42817                  1.0
ATM_0003 2022-12-05      Monday     Morning              80267           12458   Supermarket             0                   0                   115267             Rainy                       5                 83382                  0.0

--- ATM_0003 2023-05-25 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2023-05-25    Thursday       Night              27250            8253   Gas Station             0                   0                   132330             Clear                       4                 17750                  2.0
ATM_0003 2023-05-25    Thursday     Morning              34941           15725   Supermarket             0                   0                    93076            Cloudy                       1                 31029                  0.0

--- ATM_0003 2023-06-04 00:00:00 ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous

In [28]:
repeated = (
    df.groupby(["ATM_ID", "Date"])
      .size()
      .reset_index(name="Count")
)

repeated = repeated[repeated["Count"] > 1]

print("Repeated ATM-Date groups:", len(repeated))

# Check whether target is same within each repeated ATM-Date
target_check = (
    df[df.set_index(["ATM_ID", "Date"]).index.isin(
        repeated.set_index(["ATM_ID", "Date"]).index
    )]
    .groupby(["ATM_ID", "Date"])["Cash_Demand_Next_Day"]
    .nunique()
)

print("\nTarget value counts:")
print(target_check.value_counts())

Repeated ATM-Date groups: 413

Target value counts:
Cash_Demand_Next_Day
2    392
3     20
4      1
Name: count, dtype: int64

In [29]:
check = (
    df.groupby(["ATM_ID", "Date", "Time_of_Day"])
      .size()
      .reset_index(name="Count")
)

print(check[check["Count"] > 1])

        ATM_ID       Date Time_of_Day  Count
52    ATM_0001 2022-11-06       Night      2
171   ATM_0002 2023-01-05     Evening      2
178   ATM_0002 2023-02-19       Night      2
227   ATM_0002 2023-11-25   Afternoon      2
250   ATM_0003 2022-04-18       Night      2
...        ...        ...         ...    ...
5219  ATM_0047 2023-12-10   Afternoon      2
5226  ATM_0048 2022-02-08   Afternoon      2
5307  ATM_0048 2023-08-26       Night      2
5380  ATM_0049 2023-02-09       Night      2
5415  ATM_0049 2023-07-09     Morning      2

[118 rows x 4 columns]

In [30]:
print("Total ATM-Date-Time combinations:", len(check))
print("Duplicate ATM-Date-Time combinations:", (check["Count"] > 1).sum())

Total ATM-Date-Time combinations: 5540
Duplicate ATM-Date-Time combinations: 118

In [31]:
duplicates = (
    df.groupby(["ATM_ID", "Date", "Time_of_Day"])
      .size()
      .reset_index(name="Count")
)

duplicates = duplicates[duplicates["Count"] > 1]

print("Duplicate ATM-Date-Time groups:", len(duplicates))

for _, row in duplicates.head(10).iterrows():

    mask = (
        (df["ATM_ID"] == row["ATM_ID"]) &
        (df["Date"] == row["Date"]) &
        (df["Time_of_Day"] == row["Time_of_Day"])
    )

    print("\n---", row["ATM_ID"], row["Date"], row["Time_of_Day"], "---")
    print(df[mask].to_string(index=False))

Duplicate ATM-Date-Time groups: 118

--- ATM_0001 2022-11-06 00:00:00 Night ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0001 2022-11-06      Sunday       Night              77276            7579   Gas Station             0                   0                   116095            Cloudy                       5                 78121                  0.0
ATM_0001 2022-11-06      Sunday       Night              28044           12472   Gas Station             0                   0                    72323             Clear                       5                 11500                  0.0

--- ATM_0002 2023-01-05 00:00:00 Evening ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-01-05    Thursday     Evening              31855           18362   Gas Station             0                   0                   108380             Rainy                       4                 21678                 12.0
ATM_0002 2023-01-05    Thursday     Evening              31760            8770   Bank Branch             0                   0                    86322            Cloudy                       1                 30034                  0.0

--- ATM_0002 2023-02-19 00:00:00 Night ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-02-19      Sunday       Night              47633            5719   Bank Branch             0                   1                   100711             Snowy                       1                 59100                  7.0
ATM_0002 2023-02-19      Sunday       Night              55507            9567    Standalone             0                   0                   121819             Clear                       2                 60862                  0.0

--- ATM_0002 2023-11-25 00:00:00 Afternoon ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0002 2023-11-25    Saturday   Afternoon              16009            8246   Gas Station             0                   0                    95445             Clear                       2                  9494                  6.0
ATM_0002 2023-11-25    Saturday   Afternoon              59182           16015          Mall             0                   0                   123606            Cloudy                       0                 52710                  0.0

--- ATM_0003 2022-04-18 00:00:00 Night ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-04-18      Monday       Night              38791            5768    Standalone             0                   0                   124732             Rainy                       2                 33556                 11.0
ATM_0003 2022-04-18      Monday       Night              42526           15050          Mall             0                   1                    68322            Cloudy                       4                 30219                  0.0

--- ATM_0003 2022-12-05 00:00:00 Morning ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0003 2022-12-05      Monday     Morning              54844            9694   Bank Branch             0                   0                   110004            Cloudy                       0                 42817                  1.0
ATM_0003 2022-12-05      Monday     Morning              80267           12458   Supermarket             0                   0                   115267             Rainy                       5                 83382                  0.0

--- ATM_0004 2022-04-27 00:00:00 Afternoon ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0004 2022-04-27   Wednesday   Afternoon              35479            7172    Standalone             0                   0                   104018             Clear                       1                 34253                  4.0
ATM_0004 2022-04-27   Wednesday   Afternoon              39936           17079          Mall             0                   0                   120021            Cloudy                       3                 19265                  0.0

--- ATM_0004 2023-01-05 00:00:00 Morning ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0004 2023-01-05    Thursday     Morning              30102            8853   Gas Station             0                   0                    99130            Cloudy                       1                 25553                  4.0
ATM_0004 2023-01-05    Thursday     Morning              45221            4614   Supermarket             0                   0                   113267             Snowy                       3                 50538                  0.0

--- ATM_0004 2023-04-11 00:00:00 Afternoon ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0004 2023-04-11     Tuesday   Afternoon              54547            8329   Bank Branch             0                   0                    74025             Rainy                       4                 49822                  1.0
ATM_0004 2023-04-11     Tuesday   Afternoon              49833           17021   Bank Branch             0                   0                   138160             Rainy                       2                 37958                  0.0

--- ATM_0006 2022-05-21 00:00:00 Evening ---
  ATM_ID       Date Day_of_Week Time_of_Day  Total_Withdrawals  Total_Deposits Location_Type  Holiday_Flag  Special_Event_Flag  Previous_Day_Cash_Level Weather_Condition  Nearby_Competitor_ATMs  Cash_Demand_Next_Day  Days_Since_Previous
ATM_0006 2022-05-21    Saturday     Evening              48704           14182          Mall             0                   1                    78645             Clear                       5                 52127                  1.0
ATM_0006 2022-05-21    Saturday     Evening              31748            5829    Standalone             0                   0                   110850             Rainy                       0                 30928                  0.0

In [32]:
cols_to_check = [
    "Total_Withdrawals",
    "Total_Deposits",
    "Location_Type",
    "Holiday_Flag",
    "Special_Event_Flag",
    "Previous_Day_Cash_Level",
    "Weather_Condition",
    "Nearby_Competitor_ATMs",
    "Cash_Demand_Next_Day"
]

for col in cols_to_check:
    n = (
        df[df.set_index(["ATM_ID", "Date", "Time_of_Day"]).index.isin(
            duplicates.set_index(["ATM_ID", "Date", "Time_of_Day"]).index
        )]
        .groupby(["ATM_ID", "Date", "Time_of_Day"])[col]
        .nunique()
    )

    print(f"{col}:")
    print(n.value_counts().sort_index())
    print()

Total_Withdrawals:
Total_Withdrawals
2    118
Name: count, dtype: int64

Total_Deposits:
Total_Deposits
2    118
Name: count, dtype: int64

Location_Type:
Location_Type
1    22
2    96
Name: count, dtype: int64

Holiday_Flag:
Holiday_Flag
1    118
Name: count, dtype: int64

Special_Event_Flag:
Special_Event_Flag
1    98
2    20
Name: count, dtype: int64

Previous_Day_Cash_Level:
Previous_Day_Cash_Level
2    118
Name: count, dtype: int64

Weather_Condition:
Weather_Condition
1    28
2    90
Name: count, dtype: int64

Nearby_Competitor_ATMs:
Nearby_Competitor_ATMs
1    19
2    99
Name: count, dtype: int64

Cash_Demand_Next_Day:
Cash_Demand_Next_Day
2    118
Name: count, dtype: int64

In [33]:
df_clean = df.drop_duplicates(
    subset=["ATM_ID", "Date", "Time_of_Day"],
    keep="first"
).copy()

print("Original rows:", len(df))
print("Clean rows:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 5658
Clean rows: 5540
Rows removed: 118

In [34]:
print(
    df_clean.groupby(["ATM_ID", "Date", "Time_of_Day"])
    .size()
    .max()
)

1

In [35]:
df_raw = df.copy()

df_clean = df.drop_duplicates(
    subset=["ATM_ID", "Date", "Time_of_Day"],
    keep="first"
).copy()

In [36]:
print(df_clean.groupby("ATM_ID").size().describe())

count     50.000000
mean     110.800000
std       10.380515
min       90.000000
25%      105.000000
50%      110.500000
75%      116.000000
max      148.000000
dtype: float64

In [37]:
print(
    df_clean.groupby("ATM_ID")["Date"]
    .agg(["min", "max", "count"])
    .head(10)
)

                min        max  count
ATM_ID
ATM_0001 2022-01-05 2023-12-16    119
ATM_0002 2022-01-05 2024-01-01    114
ATM_0003 2022-01-01 2023-12-22    109
ATM_0004 2022-01-03 2024-01-01     98
ATM_0005 2022-01-10 2023-12-25     90
ATM_0006 2022-01-08 2023-12-30    126
ATM_0007 2022-01-02 2023-12-25    123
ATM_0008 2022-01-01 2024-01-01    114
ATM_0009 2022-01-09 2023-12-30    117
ATM_0010 2022-01-13 2023-12-27    116

In [38]:
print(
    df_clean["Time_of_Day"]
    .value_counts()
)

Time_of_Day
Afternoon    1425
Evening      1396
Night        1395
Morning      1324
Name: count, dtype: int64

In [39]:
df_clean["Days_Since_Previous"] = (
    df_clean.groupby("ATM_ID")["Date"]
    .diff()
    .dt.days
)

print(df_clean["Days_Since_Previous"].describe())

print("\nGap distribution:")
print(
    df_clean["Days_Since_Previous"]
    .value_counts()
    .sort_index()
    .head(30)
)

count    5490.000000
mean        6.555373
std         6.349992
min         0.000000
25%         2.000000
50%         5.000000
75%         9.000000
max        52.000000
Name: Days_Since_Previous, dtype: float64

Gap distribution:
Days_Since_Previous
0.0     317
1.0     802
2.0     575
3.0     535
4.0     473
5.0     378
6.0     336
7.0     307
8.0     249
9.0     213
10.0    185
11.0    162
12.0    146
13.0    126
14.0    103
15.0     76
16.0     64
17.0     62
18.0     56
19.0     40
20.0     52
21.0     33
22.0     37
23.0     25
24.0     33
25.0     18
26.0     14
27.0     12
28.0     11
29.0      4
Name: count, dtype: int64

In [40]:
dates_per_atm = (
    df_clean.groupby("ATM_ID")["Date"]
    .nunique()
)

print(dates_per_atm.describe())

count     50.000000
mean     104.460000
std        9.721027
min       81.000000
25%       97.250000
50%      105.000000
75%      110.750000
max      136.000000
Name: Date, dtype: float64

In [42]:
print(
    df_clean[
        [
            "Total_Withdrawals",
            "Total_Deposits",
            "Previous_Day_Cash_Level",
            "Cash_Demand_Next_Day"
        ]
    ].corr()
)

                         Total_Withdrawals  Total_Deposits  \
Total_Withdrawals                 1.000000       -0.002615
Total_Deposits                   -0.002615        1.000000
Previous_Day_Cash_Level          -0.012246       -0.012288
Cash_Demand_Next_Day              0.895098       -0.216192

                         Previous_Day_Cash_Level  Cash_Demand_Next_Day
Total_Withdrawals                      -0.012246              0.895098
Total_Deposits                         -0.012288             -0.216192
Previous_Day_Cash_Level                 1.000000             -0.009745
Cash_Demand_Next_Day                   -0.009745              1.000000

In [43]:
print(
    df_clean[
        [
            "Total_Withdrawals",
            "Total_Deposits",
            "Previous_Day_Cash_Level",
            "Cash_Demand_Next_Day"
        ]
    ].describe()
)

       Total_Withdrawals  Total_Deposits  Previous_Day_Cash_Level  \
count        5540.000000     5540.000000              5540.000000
mean        49785.461011    10115.158484            100345.400542
std         14915.653754     4877.167099             20106.364598
min          1380.000000        0.000000             23266.000000
25%         39441.000000     6765.000000             86568.500000
50%         50039.000000    10033.000000            100308.500000
75%         60101.250000    13420.250000            113979.500000
max        107790.000000    32395.000000            172227.000000

       Cash_Demand_Next_Day
count           5540.000000
mean           43079.951986
std            16821.716778
min                0.000000
25%            31576.750000
50%            42544.000000
75%            53879.000000
max           114724.000000

In [44]:
import numpy as np

df_clean["Withdrawal_Target_Ratio"] = (
    df_clean["Cash_Demand_Next_Day"] /
    df_clean["Total_Withdrawals"]
)

print(df_clean["Withdrawal_Target_Ratio"].describe())

count    5540.000000
mean        0.846609
std         0.177375
min         0.000000
25%         0.741145
50%         0.855221
75%         0.969000
max         2.065483
Name: Withdrawal_Target_Ratio, dtype: float64

In [45]:
print(
    df_clean[
        ["Total_Withdrawals", "Cash_Demand_Next_Day", "Withdrawal_Target_Ratio"]
    ].head(20)
)

    Total_Withdrawals  Cash_Demand_Next_Day  Withdrawal_Target_Ratio
0               37573                 31478                 0.837782
1               48156                 41613                 0.864129
2               24671                 11316                 0.458676
3               46383                 34587                 0.745683
4               41972                 23665                 0.563828
5               57436                 40364                 0.702765
6               51743                 38910                 0.751986
7               63303                 63926                 1.009842
8               61950                 62604                 1.010557
9               54368                 63865                 1.174680
10              40466                 28441                 0.702837
11              70415                 54469                 0.773543
12              38826                 37733                 0.971849
13              44099                 33879                 0.768249
14              58494                 44974                 0.768865
15              82159                 83492                 1.016225
16              49580                 45705                 0.921843
17              40242                 21415                 0.532155
18              38066                 27375                 0.719146
19              46816                 43740                 0.934296

In [46]:
print(
    df_clean["Withdrawal_Target_Ratio"]
    .round(2)
    .value_counts()
    .head(20)
)

Withdrawal_Target_Ratio
0.87    159
0.85    146
0.80    140
0.86    138
0.94    134
0.84    133
0.88    130
0.78    128
0.91    128
0.83    123
0.75    121
0.96    119
0.81    118
0.82    115
0.90    114
0.79    113
0.95    112
0.77    110
0.92    108
0.89    105
Name: count, dtype: int64

In [47]:
df_clean = df_clean.drop(columns=["Withdrawal_Target_Ratio"])

In [49]:
df_clean["Year"] = df_clean["Date"].dt.year
df_clean["Month"] = df_clean["Date"].dt.month
df_clean["Day"] = df_clean["Date"].dt.day
df_clean["Day_of_Week_Num"] = df_clean["Date"].dt.dayofweek
df_clean["Is_Weekend"] = (
    df_clean["Date"].dt.dayofweek >= 5
).astype(int)

In [50]:
print(
    df_clean[
        [
            "Date",
            "Year",
            "Month",
            "Day",
            "Day_of_Week_Num",
            "Is_Weekend"
        ]
    ].head(10)
)

        Date  Year  Month  Day  Day_of_Week_Num  Is_Weekend
0 2022-01-05  2022      1    5                2           0
1 2022-01-13  2022      1   13                3           0
2 2022-01-20  2022      1   20                3           0
3 2022-01-28  2022      1   28                4           0
4 2022-02-01  2022      2    1                1           0
5 2022-02-24  2022      2   24                3           0
6 2022-02-27  2022      2   27                6           1
7 2022-03-05  2022      3    5                5           1
8 2022-03-05  2022      3    5                5           1
9 2022-03-08  2022      3    8                1           0

In [51]:
print(df_clean.shape)
print(df_clean.columns.tolist())

(5540, 19)
['ATM_ID', 'Date', 'Day_of_Week', 'Time_of_Day', 'Total_Withdrawals', 'Total_Deposits', 'Location_Type', 'Holiday_Flag', 'Special_Event_Flag', 'Previous_Day_Cash_Level', 'Weather_Condition', 'Nearby_Competitor_ATMs', 'Cash_Demand_Next_Day', 'Days_Since_Previous', 'Year', 'Month', 'Day', 'Day_of_Week_Num', 'Is_Weekend']

In [52]:
categorical_cols = [
    "ATM_ID",
    "Time_of_Day",
    "Location_Type",
    "Weather_Condition"
]

df_model = pd.get_dummies(
    df_clean,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

print(df_model.shape)
print(df_model.head())

(5540, 74)
        Date Day_of_Week  Total_Withdrawals  Total_Deposits  Holiday_Flag  \
0 2022-01-05   Wednesday              37573            6224             0
1 2022-01-13    Thursday              48156           10070             0
2 2022-01-20    Thursday              24671           13922             0
3 2022-01-28      Friday              46383           12205             0
4 2022-02-01     Tuesday              41972           18452             0

   Special_Event_Flag  Previous_Day_Cash_Level  Nearby_Competitor_ATMs  \
0                   1                   109776                       4
1                   1                   113068                       5
2                   0                   118171                       4
3                   0                    96931                       4
4                   0                    83257                       5

   Cash_Demand_Next_Day  Days_Since_Previous  ...  Time_of_Day_Evening  \
0                 31478                  NaN  ...                    0
1                 41613                  8.0  ...                    0
2                 11316                  7.0  ...                    1
3                 34587                  8.0  ...                    0
4                 23665                  4.0  ...                    0

   Time_of_Day_Morning  Time_of_Day_Night  Location_Type_Gas Station  \
0                    0                  1                          0
1                    1                  0                          1
2                    0                  0                          0
3                    0                  1                          0
4                    1                  0                          0

   Location_Type_Mall  Location_Type_Standalone  Location_Type_Supermarket  \
0                   0                         1                          0
1                   0                         0                          0
2                   1                         0                          0
3                   1                         0                          0
4                   0                         0                          0

   Weather_Condition_Cloudy  Weather_Condition_Rainy  Weather_Condition_Snowy
0                         0                        0                        0
1                         0                        0                        0
2                         0                        1                        0
3                         0                        0                        0
4                         0                        1                        0

[5 rows x 74 columns]

In [53]:
print(df_model.dtypes)

Date                         datetime64[us]
Day_of_Week                             str
Total_Withdrawals                     int64
Total_Deposits                        int64
Holiday_Flag                          int64
                                  ...
Location_Type_Standalone              int64
Location_Type_Supermarket             int64
Weather_Condition_Cloudy              int64
Weather_Condition_Rainy               int64
Weather_Condition_Snowy               int64
Length: 74, dtype: object

In [54]:
df_model = df_model.drop(columns=["Day_of_Week"])

print(df_model.dtypes[df_model.dtypes == "object"])

Series([], dtype: object)

In [56]:
df_model["Previous_Observed_Demand"] = (
    df_clean.groupby("ATM_ID")["Cash_Demand_Next_Day"].shift(1)
)

In [57]:
print(
    df_model[
        [
            "Date",
            "Cash_Demand_Next_Day",
            "Days_Since_Previous",
            "Previous_Observed_Demand"
        ]
    ].head(15)
)

         Date  Cash_Demand_Next_Day  Days_Since_Previous  \
0  2022-01-05                 31478                  NaN
1  2022-01-13                 41613                  8.0
2  2022-01-20                 11316                  7.0
3  2022-01-28                 34587                  8.0
4  2022-02-01                 23665                  4.0
5  2022-02-24                 40364                 23.0
6  2022-02-27                 38910                  3.0
7  2022-03-05                 63926                  6.0
8  2022-03-05                 62604                  0.0
9  2022-03-08                 63865                  3.0
10 2022-03-17                 28441                  9.0
11 2022-03-18                 54469                  1.0
12 2022-04-06                 37733                 19.0
13 2022-04-11                 33879                  5.0
14 2022-04-12                 44974                  1.0

    Previous_Observed_Demand
0                        NaN
1                    31478.0
2                    41613.0
3                    11316.0
4                    34587.0
5                    23665.0
6                    40364.0
7                    38910.0
8                    63926.0
9                    62604.0
10                   63865.0
11                   28441.0
12                   54469.0
13                   37733.0
14                   33879.0

In [59]:
daily_counts = (
    df_clean.groupby(["ATM_ID", "Date"])
    .size()
    .reset_index(name="Observations")
)

print(daily_counts["Observations"].value_counts().sort_index())

Observations
1    4915
2     300
3       7
4       1
Name: count, dtype: int64

In [60]:
print(daily_counts["Observations"].describe())

count    5223.000000
mean        1.060693
std         0.246679
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         4.000000
Name: Observations, dtype: float64

In [61]:
print("Minimum date:", df_clean["Date"].min())
print("Maximum date:", df_clean["Date"].max())

Minimum date: 2022-01-01 00:00:00
Maximum date: 2024-01-01 00:00:00

In [62]:
print(
    df_clean["Date"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

Date
2022-01    208
2022-02    211
2022-03    237
2022-04    237
2022-05    248
2022-06    202
2022-07    238
2022-08    213
2022-09    227
2022-10    228
2022-11    252
2022-12    233
2023-01    234
2023-02    234
2023-03    239
2023-04    241
2023-05    222
2023-06    196
2023-07    235
2023-08    231
2023-09    230
2023-10    244
2023-11    233
2023-12    257
2024-01     10
Freq: M, Name: count, dtype: int64

In [63]:
date_70 = df_clean["Date"].quantile(0.70)
date_85 = df_clean["Date"].quantile(0.85)

print("70% cutoff:", date_70)
print("85% cutoff:", date_85)

70% cutoff: 2023-05-28 00:00:00
85% cutoff: 2023-09-18 00:00:00

In [64]:
train = df_model[df_model["Date"] < "2023-05-28"].copy()

val = df_model[
    (df_model["Date"] >= "2023-05-28") &
    (df_model["Date"] < "2023-09-18")
].copy()

test = df_model[df_model["Date"] >= "2023-09-18"].copy()

print("Train:", train.shape)
print("Validation:", val.shape)
print("Test:", test.shape)

Train: (3876, 74)
Validation: (830, 74)
Test: (834, 74)

In [65]:
print("\nTrain dates:", train["Date"].min(), "→", train["Date"].max())
print("Val dates:", val["Date"].min(), "→", val["Date"].max())
print("Test dates:", test["Date"].min(), "→", test["Date"].max())

Train dates: 2022-01-01 00:00:00 → 2023-05-27 00:00:00
Val dates: 2023-05-28 00:00:00 → 2023-09-17 00:00:00
Test dates: 2023-09-18 00:00:00 → 2024-01-01 00:00:00

In [66]:
target = "Cash_Demand_Next_Day"

X_train = train.drop(columns=[target, "Date"])
y_train = train[target]

X_val = val.drop(columns=[target, "Date"])
y_val = val[target]

X_test = test.drop(columns=[target, "Date"])
y_test = test[target]

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

X_train: (3876, 72)
X_val: (830, 72)
X_test: (834, 72)

In [67]:
print("NaN values in X_train:")
print(X_train.isna().sum()[X_train.isna().sum() > 0])

print("\nNaN values in X_val:")
print(X_val.isna().sum()[X_val.isna().sum() > 0])

print("\nNaN values in X_test:")
print(X_test.isna().sum()[X_test.isna().sum() > 0])

NaN values in X_train:
Days_Since_Previous         50
Previous_Observed_Demand    50
dtype: int64

NaN values in X_val:
Series([], dtype: int64)

NaN values in X_test:
Series([], dtype: int64)

In [68]:
print("Infinite values:", np.isinf(X_train.select_dtypes(include=np.number)).sum().sum())

Infinite values: 0

In [69]:
drop_features = [
    "Days_Since_Previous",
    "Previous_Observed_Demand"
]

X_train = X_train.drop(columns=drop_features)
X_val = X_val.drop(columns=drop_features)
X_test = X_test.drop(columns=drop_features)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

X_train: (3876, 70)
X_val: (830, 70)
X_test: (834, 70)

In [70]:
print("NaNs:", X_train.isna().sum().sum())
print("NaNs:", X_val.isna().sum().sum())
print("NaNs:", X_test.isna().sum().sum())

NaNs: 0
NaNs: 0
NaNs: 0

In [71]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model_lr = LinearRegression()

model_lr.fit(X_train, y_train)

y_val_pred = model_lr.predict(X_val)

mae = mean_absolute_error(y_val, y_val_pred)
rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))
r2 = r2_score(y_val, y_val_pred)

print("Linear Regression — Validation")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

Linear Regression — Validation
MAE : 5262.399048377658
RMSE: 6266.108484203608
R²  : 0.8635537013663934

In [72]:
from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor(
    random_state=42,
    max_depth=10
)

model_dt.fit(X_train, y_train)

y_val_pred_dt = model_dt.predict(X_val)

mae_dt = mean_absolute_error(y_val, y_val_pred_dt)
rmse_dt = np.sqrt(mean_squared_error(y_val, y_val_pred_dt))
r2_dt = r2_score(y_val, y_val_pred_dt)

print("Decision Tree — Validation")
print("MAE :", mae_dt)
print("RMSE:", rmse_dt)
print("R²  :", r2_dt)

Decision Tree — Validation
MAE : 6236.7384728914685
RMSE: 7721.599077579407
R²  : 0.7928044437411255

In [73]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)

model_rf.fit(X_train, y_train)

y_val_pred_rf = model_rf.predict(X_val)

mae_rf = mean_absolute_error(y_val, y_val_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_val, y_val_pred_rf))
r2_rf = r2_score(y_val, y_val_pred_rf)

print("Random Forest — Validation")
print("MAE :", mae_rf)
print("RMSE:", rmse_rf)
print("R²  :", r2_rf)

Random Forest — Validation
MAE : 5338.024446184747
RMSE: 6408.318948609276
R²  : 0.8572900749941079

In [74]:
from sklearn.ensemble import GradientBoostingRegressor

model_gb = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

model_gb.fit(X_train, y_train)

y_val_pred_gb = model_gb.predict(X_val)

mae_gb = mean_absolute_error(y_val, y_val_pred_gb)
rmse_gb = np.sqrt(mean_squared_error(y_val, y_val_pred_gb))
r2_gb = r2_score(y_val, y_val_pred_gb)

print("Gradient Boosting — Validation")
print("MAE :", mae_gb)
print("RMSE:", rmse_gb)
print("R²  :", r2_gb)

Gradient Boosting — Validation
MAE : 5276.770205441317
RMSE: 6285.630225536344
R²  : 0.8627021940497084

In [75]:
from sklearn.ensemble import HistGradientBoostingRegressor

model_hgb = HistGradientBoostingRegressor(
    max_iter=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

model_hgb.fit(X_train, y_train)

y_val_pred_hgb = model_hgb.predict(X_val)

mae_hgb = mean_absolute_error(y_val, y_val_pred_hgb)
rmse_hgb = np.sqrt(mean_squared_error(y_val, y_val_pred_hgb))
r2_hgb = r2_score(y_val, y_val_pred_hgb)

print("HistGradientBoosting — Validation")
print("MAE :", mae_hgb)
print("RMSE:", rmse_hgb)
print("R²  :", r2_hgb)

HistGradientBoosting — Validation
MAE : 5375.9139733791035
RMSE: 6462.633200938692
R²  : 0.8548607231331934

In [77]:
df_ts = df_clean.copy()

df_ts = df_ts.sort_values(
    ["ATM_ID", "Date", "Time_of_Day"]
).reset_index(drop=True)

In [78]:
df_ts["Previous_Demand"] = (
    df_ts.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .shift(1)
)

In [79]:
df_ts["Previous_Observed_Demand"] = (
    df_ts.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .shift(1)
)

In [80]:
df_ts["Rolling_Mean_Demand_3"] = (
    df_ts.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)
df_ts["Rolling_Mean_Demand_7"] = (
    df_ts.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

In [82]:
print(
    df_ts[
        [
            "ATM_ID",
            "Date",
            "Time_of_Day",
            "Cash_Demand_Next_Day",
            "Previous_Observed_Demand",
            "Rolling_Mean_Demand_3",
            "Rolling_Mean_Demand_7"
        ]
    ].head(15)
)

      ATM_ID       Date Time_of_Day  Cash_Demand_Next_Day  \
0   ATM_0001 2022-01-05       Night                 31478
1   ATM_0001 2022-01-13     Morning                 41613
2   ATM_0001 2022-01-20     Evening                 11316
3   ATM_0001 2022-01-28       Night                 34587
4   ATM_0001 2022-02-01     Morning                 23665
5   ATM_0001 2022-02-24     Evening                 40364
6   ATM_0001 2022-02-27       Night                 38910
7   ATM_0001 2022-03-05   Afternoon                 63926
8   ATM_0001 2022-03-05     Morning                 62604
9   ATM_0001 2022-03-08       Night                 63865
10  ATM_0001 2022-03-17     Evening                 28441
11  ATM_0001 2022-03-18   Afternoon                 54469
12  ATM_0001 2022-04-06       Night                 37733
13  ATM_0001 2022-04-11       Night                 33879
14  ATM_0001 2022-04-12       Night                 44974

    Previous_Observed_Demand  Rolling_Mean_Demand_3  Rolling_Mean_Demand_7
0                        NaN                    NaN                    NaN
1                    31478.0                    NaN                    NaN
2                    41613.0                    NaN                    NaN
3                    11316.0           28135.666667                    NaN
4                    34587.0           29172.000000                    NaN
5                    23665.0           23189.333333                    NaN
6                    40364.0           32872.000000                    NaN
7                    38910.0           34313.000000           31704.714286
8                    63926.0           47733.333333           36340.142857
9                    62604.0           55146.666667           39338.857143
10                   63865.0           63465.000000           46845.857143
11                   28441.0           51636.666667           45967.857143
12                   54469.0           48925.000000           50368.428571
13                   37733.0           40214.333333           49992.571429
14                   33879.0           42027.000000           49273.857143

In [83]:
df_ts["Previous_Date"] = (
    df_ts.groupby("ATM_ID")["Date"].shift(1)
)

df_ts["Previous_Date_Demand"] = (
    df_ts.groupby("ATM_ID")["Cash_Demand_Next_Day"].shift(1)
)

df_ts.loc[
    df_ts["Date"] == df_ts["Previous_Date"],
    "Previous_Date_Demand"
] = np.nan

In [84]:
print(
    df_ts[
        [
            "ATM_ID",
            "Date",
            "Time_of_Day",
            "Cash_Demand_Next_Day",
            "Previous_Date",
            "Previous_Date_Demand"
        ]
    ].head(15)
)

      ATM_ID       Date Time_of_Day  Cash_Demand_Next_Day Previous_Date  \
0   ATM_0001 2022-01-05       Night                 31478           NaT
1   ATM_0001 2022-01-13     Morning                 41613    2022-01-05
2   ATM_0001 2022-01-20     Evening                 11316    2022-01-13
3   ATM_0001 2022-01-28       Night                 34587    2022-01-20
4   ATM_0001 2022-02-01     Morning                 23665    2022-01-28
5   ATM_0001 2022-02-24     Evening                 40364    2022-02-01
6   ATM_0001 2022-02-27       Night                 38910    2022-02-24
7   ATM_0001 2022-03-05   Afternoon                 63926    2022-02-27
8   ATM_0001 2022-03-05     Morning                 62604    2022-03-05
9   ATM_0001 2022-03-08       Night                 63865    2022-03-05
10  ATM_0001 2022-03-17     Evening                 28441    2022-03-08
11  ATM_0001 2022-03-18   Afternoon                 54469    2022-03-17
12  ATM_0001 2022-04-06       Night                 37733    2022-03-18
13  ATM_0001 2022-04-11       Night                 33879    2022-04-06
14  ATM_0001 2022-04-12       Night                 44974    2022-04-11

    Previous_Date_Demand
0                    NaN
1                31478.0
2                41613.0
3                11316.0
4                34587.0
5                23665.0
6                40364.0
7                38910.0
8                    NaN
9                62604.0
10               63865.0
11               28441.0
12               54469.0
13               37733.0
14               33879.0

In [88]:
df_ts["Rolling_Mean_Demand_3"] = (
    df_ts.groupby("ATM_ID")["Previous_Date_Demand"]
    .transform(lambda x: x.rolling(3).mean())
)

df_ts["Rolling_Mean_Demand_7"] = (
    df_ts.groupby("ATM_ID")["Previous_Date_Demand"]
    .transform(lambda x: x.rolling(7).mean())
)

In [89]:
daily_demand = (
    df_ts.groupby(["ATM_ID", "Date"])["Cash_Demand_Next_Day"]
    .mean()
    .reset_index()
)

In [90]:
daily_demand = daily_demand.sort_values(
    ["ATM_ID", "Date"]
).reset_index(drop=True)

daily_demand["Previous_Day_Demand"] = (
    daily_demand.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .shift(1)
)

daily_demand["Rolling_Mean_3_Days"] = (
    daily_demand.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

daily_demand["Rolling_Mean_7_Days"] = (
    daily_demand.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

In [91]:
historical_features = daily_demand[
    [
        "ATM_ID",
        "Date",
        "Previous_Day_Demand",
        "Rolling_Mean_3_Days",
        "Rolling_Mean_7_Days"
    ]
]

df_ts = df_ts.merge(
    historical_features,
    on=["ATM_ID", "Date"],
    how="left"
)

In [92]:
print(
    df_ts[
        [
            "ATM_ID",
            "Date",
            "Time_of_Day",
            "Cash_Demand_Next_Day",
            "Previous_Day_Demand",
            "Rolling_Mean_3_Days",
            "Rolling_Mean_7_Days"
        ]
    ].head(15)
)

      ATM_ID       Date Time_of_Day  Cash_Demand_Next_Day  \
0   ATM_0001 2022-01-05       Night                 31478
1   ATM_0001 2022-01-13     Morning                 41613
2   ATM_0001 2022-01-20     Evening                 11316
3   ATM_0001 2022-01-28       Night                 34587
4   ATM_0001 2022-02-01     Morning                 23665
5   ATM_0001 2022-02-24     Evening                 40364
6   ATM_0001 2022-02-27       Night                 38910
7   ATM_0001 2022-03-05   Afternoon                 63926
8   ATM_0001 2022-03-05     Morning                 62604
9   ATM_0001 2022-03-08       Night                 63865
10  ATM_0001 2022-03-17     Evening                 28441
11  ATM_0001 2022-03-18   Afternoon                 54469
12  ATM_0001 2022-04-06       Night                 37733
13  ATM_0001 2022-04-11       Night                 33879
14  ATM_0001 2022-04-12       Night                 44974

    Previous_Day_Demand  Rolling_Mean_3_Days  Rolling_Mean_7_Days
0                   NaN                  NaN                  NaN
1               31478.0                  NaN                  NaN
2               41613.0                  NaN                  NaN
3               11316.0         28135.666667                  NaN
4               34587.0         29172.000000                  NaN
5               23665.0         23189.333333                  NaN
6               40364.0         32872.000000                  NaN
7               38910.0         34313.000000         31704.714286
8               38910.0         34313.000000         31704.714286
9               63265.0         47513.000000         36245.714286
10              63865.0         55346.666667         39424.571429
11              28441.0         51857.000000         41871.000000
12              54469.0         48925.000000         44711.285714
13              37733.0         40214.333333         46721.000000
14              33879.0         42027.000000         45794.571429

In [93]:
df_ts_model = df_ts.dropna(
    subset=[
        "Previous_Day_Demand",
        "Rolling_Mean_3_Days",
        "Rolling_Mean_7_Days"
    ]
).copy()

In [94]:
print("Original rows:", len(df_ts))
print("Rows after removing NaNs:", len(df_ts_model))

Original rows: 5540
Rows after removing NaNs: 5169

In [95]:
df_ts_model["Year"] = df_ts_model["Date"].dt.year
df_ts_model["Month"] = df_ts_model["Date"].dt.month
df_ts_model["Day"] = df_ts_model["Date"].dt.day
df_ts_model["Day_of_Week_Num"] = df_ts_model["Date"].dt.dayofweek
df_ts_model["Is_Weekend"] = (
    df_ts_model["Date"].dt.dayofweek >= 5
).astype(int)

In [96]:
categorical_cols = [
    "ATM_ID",
    "Time_of_Day",
    "Location_Type",
    "Weather_Condition"
]

df_ts_model = pd.get_dummies(
    df_ts_model,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

df_ts_model = df_ts_model.drop(
    columns=["Day_of_Week"]
)

In [97]:
train_ts = df_ts_model[
    df_ts_model["Date"] < "2023-05-28"
].copy()

val_ts = df_ts_model[
    (df_ts_model["Date"] >= "2023-05-28") &
    (df_ts_model["Date"] < "2023-09-18")
].copy()

test_ts = df_ts_model[
    df_ts_model["Date"] >= "2023-09-18"
].copy()

In [98]:
target = "Cash_Demand_Next_Day"

X_train_ts = train_ts.drop(
    columns=[target, "Date"]
)
y_train_ts = train_ts[target]

X_val_ts = val_ts.drop(
    columns=[target, "Date"]
)
y_val_ts = val_ts[target]

X_test_ts = test_ts.drop(
    columns=[target, "Date"]
)
y_test_ts = test_ts[target]

In [99]:
print("Train:", X_train_ts.shape)
print("Validation:", X_val_ts.shape)
print("Test:", X_test_ts.shape)

Train: (3505, 80)
Validation: (830, 80)
Test: (834, 80)

In [101]:
print(X_train_ts.select_dtypes(include=["datetime"]).columns)

Index(['Previous_Date'], dtype='str')

In [102]:
X_train_ts = X_train_ts.drop(columns=["Previous_Date"], errors="ignore")
X_val_ts = X_val_ts.drop(columns=["Previous_Date"], errors="ignore")
X_test_ts = X_test_ts.drop(columns=["Previous_Date"], errors="ignore")

In [103]:
print(X_train_ts.select_dtypes(exclude=["number"]).columns)

Index([], dtype='str')

In [105]:
nan_counts = X_train_ts.isna().sum()

print(nan_counts[nan_counts > 0])

Rolling_Mean_Demand_3     552
Rolling_Mean_Demand_7    1166
Previous_Date_Demand      194
dtype: int64

In [108]:
old_features = [
    "Previous_Observed_Demand",
    "Rolling_Mean_Demand_3",
    "Rolling_Mean_Demand_7"
]

X_train_ts = X_train_ts.drop(columns=old_features, errors="ignore")
X_val_ts = X_val_ts.drop(columns=old_features, errors="ignore")
X_test_ts = X_test_ts.drop(columns=old_features, errors="ignore")

In [109]:
print(X_train_ts.isna().sum()[X_train_ts.isna().sum() > 0])

Previous_Date_Demand    194
dtype: int64

In [110]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train_ts[["Previous_Date_Demand"]] = imputer.fit_transform(
    X_train_ts[["Previous_Date_Demand"]]
)

X_val_ts[["Previous_Date_Demand"]] = imputer.transform(
    X_val_ts[["Previous_Date_Demand"]]
)

X_test_ts[["Previous_Date_Demand"]] = imputer.transform(
    X_test_ts[["Previous_Date_Demand"]]
)

In [111]:
print("Train NaNs:", X_train_ts.isna().sum().sum())
print("Validation NaNs:", X_val_ts.isna().sum().sum())
print("Test NaNs:", X_test_ts.isna().sum().sum())

Train NaNs: 0
Validation NaNs: 0
Test NaNs: 0

In [112]:
model_lr_ts = LinearRegression()

model_lr_ts.fit(X_train_ts, y_train_ts)

y_val_pred_lr_ts = model_lr_ts.predict(X_val_ts)

mae_lr_ts = mean_absolute_error(y_val_ts, y_val_pred_lr_ts)
rmse_lr_ts = np.sqrt(mean_squared_error(y_val_ts, y_val_pred_lr_ts))
r2_lr_ts = r2_score(y_val_ts, y_val_pred_lr_ts)

print("Linear Regression + Historical Features — Validation")
print("MAE :", mae_lr_ts)
print("RMSE:", rmse_lr_ts)
print("R²  :", r2_lr_ts)

Linear Regression + Historical Features — Validation
MAE : 5273.8632312509735
RMSE: 6284.357781449001
R²  : 0.8627577767333422

In [113]:
coef_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model_lr.coef_
})

coef_df["Absolute_Coefficient"] = coef_df["Coefficient"].abs()

coef_df = coef_df.sort_values(
    "Absolute_Coefficient",
    ascending=False
)

print(coef_df.head(20))

               Feature  Coefficient  Absolute_Coefficient
3   Special_Event_Flag  7233.743470           7233.743470
2         Holiday_Flag  4889.469805           4889.469805
26     ATM_ID_ATM_0017  2026.179561           2026.179561
38     ATM_ID_ATM_0029  1896.562564           1896.562564
40     ATM_ID_ATM_0031  1836.592770           1836.592770
32     ATM_ID_ATM_0023  1803.954736           1803.954736
48     ATM_ID_ATM_0039  1605.314965           1605.314965
13     ATM_ID_ATM_0004  1601.238311           1601.238311
20     ATM_ID_ATM_0011  1352.902871           1352.902871
14     ATM_ID_ATM_0005  1344.185536           1344.185536
24     ATM_ID_ATM_0015  1257.942248           1257.942248
42     ATM_ID_ATM_0033  1225.625780           1225.625780
18     ATM_ID_ATM_0009  1220.747787           1220.747787
43     ATM_ID_ATM_0034  1051.977040           1051.977040
33     ATM_ID_ATM_0024  1048.080576           1048.080576
47     ATM_ID_ATM_0038  1035.763804           1035.763804
50     ATM_ID_ATM_0041   903.787273            903.787273
25     ATM_ID_ATM_0016   870.328299            870.328299
23     ATM_ID_ATM_0014   850.655634            850.655634
37     ATM_ID_ATM_0028   836.236496            836.236496

In [114]:
print("Top Positive Coefficients:")
print(
    coef_df.sort_values(
        "Coefficient",
        ascending=False
    )[["Feature", "Coefficient"]].head(10)
)

print("\nTop Negative Coefficients:")
print(
    coef_df.sort_values(
        "Coefficient"
    )[["Feature", "Coefficient"]].head(10)
)

Top Positive Coefficients:
               Feature  Coefficient
3   Special_Event_Flag  7233.743470
2         Holiday_Flag  4889.469805
26     ATM_ID_ATM_0017  2026.179561
38     ATM_ID_ATM_0029  1896.562564
40     ATM_ID_ATM_0031  1836.592770
32     ATM_ID_ATM_0023  1803.954736
48     ATM_ID_ATM_0039  1605.314965
13     ATM_ID_ATM_0004  1601.238311
20     ATM_ID_ATM_0011  1352.902871
14     ATM_ID_ATM_0005  1344.185536

Top Negative Coefficients:
                      Feature  Coefficient
58            ATM_ID_ATM_0049  -719.331941
31            ATM_ID_ATM_0022  -519.038789
59            ATM_ID_ATM_0050  -465.763831
16            ATM_ID_ATM_0007  -443.362696
22            ATM_ID_ATM_0013  -371.885622
51            ATM_ID_ATM_0042  -366.959750
60        Time_of_Day_Evening  -193.368720
17            ATM_ID_ATM_0008  -181.942819
63  Location_Type_Gas Station  -180.289969
62          Time_of_Day_Night  -174.767631

In [115]:
contribution_df = pd.DataFrame(
    X_train.values * model_lr.coef_,
    columns=X_train.columns
)

contribution_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Mean_Absolute_Contribution": contribution_df.abs().mean().values
})

contribution_df = contribution_df.sort_values(
    "Mean_Absolute_Contribution",
    ascending=False
)

print(contribution_df.head(20))

                      Feature  Mean_Absolute_Contribution
6                        Year               200241.510042
0           Total_Withdrawals                50256.701224
1              Total_Deposits                 7527.315257
3          Special_Event_Flag                  690.527627
4     Previous_Day_Cash_Level                  589.406134
9             Day_of_Week_Num                  249.966194
10                 Is_Weekend                  145.954314
8                         Day                  139.226200
67   Weather_Condition_Cloudy                  127.935122
2                Holiday_Flag                  103.440796
7                       Month                   78.451845
64         Location_Type_Mall                   74.554931
69    Weather_Condition_Snowy                   50.942431
60        Time_of_Day_Evening                   48.741290
5      Nearby_Competitor_ATMs                   45.855911
62          Time_of_Day_Night                   43.872266
26            ATM_ID_ATM_0017                   38.683511
40            ATM_ID_ATM_0031                   38.380809
61        Time_of_Day_Morning                   37.939120
63  Location_Type_Gas Station                   36.746408

In [116]:
print(
    coef_df[coef_df["Feature"] == "Year"]
)
print("Year coefficient:", model_lr.coef_[X_train.columns.get_loc("Year")])
print(
    df_clean.groupby("Year")["Cash_Demand_Next_Day"].agg(
        ["count", "mean", "std"]
    )
)

  Feature  Coefficient  Absolute_Coefficient
6    Year   -99.016981             99.016981
Year coefficient: -99.0169813590876
      count          mean           std
Year
2022   2734  42890.950622  16729.724173
2023   2796  43227.671674  16891.159478
2024     10  53450.500000  20468.038625

In [117]:
X_train_no_year = X_train.drop(columns=["Year"])
X_val_no_year = X_val.drop(columns=["Year"])
X_test_no_year = X_test.drop(columns=["Year"])

In [118]:
model_lr_no_year = LinearRegression()

model_lr_no_year.fit(
    X_train_no_year,
    y_train
)

y_val_pred_no_year = model_lr_no_year.predict(
    X_val_no_year
)

mae_no_year = mean_absolute_error(
    y_val,
    y_val_pred_no_year
)

rmse_no_year = np.sqrt(
    mean_squared_error(y_val, y_val_pred_no_year)
)

r2_no_year = r2_score(
    y_val,
    y_val_pred_no_year
)

print("Linear Regression — Without Year")
print("MAE :", mae_no_year)
print("RMSE:", rmse_no_year)
print("R²  :", r2_no_year)

Linear Regression — Without Year
MAE : 5258.761137011362
RMSE: 6263.032554695501
R²  : 0.8636876269712832

In [119]:
residuals = y_val - y_val_pred_no_year

print("Mean Residual:", residuals.mean())
print("Min Residual :", residuals.min())
print("Max Residual :", residuals.max())

Mean Residual: 221.16264317961185
Min Residual : -15455.343225981516
Max Residual : 16302.14683920439

In [120]:
print(
    pd.DataFrame({
        "Actual": y_val,
        "Predicted": y_val_pred_no_year,
        "Residual": residuals
    }).head(10)
)

    Actual     Predicted      Residual
80   56182  49360.381889   6821.618111
81   46385  40771.028502   5613.971498
82   44997  49261.623721  -4264.623721
83   58361  55474.951221   2886.048779
84   48968  54681.941071  -5713.941071
85   54203  59675.091376  -5472.091376
86   80647  69926.044973  10720.955027
87   48417  49942.288590  -1525.288590
88   38527  35213.629873   3313.370127
89   70814  63387.855306   7426.144694

In [121]:
residual_df = pd.DataFrame({
    "Actual": y_val,
    "Predicted": y_val_pred_no_year,
    "Residual": residuals
})

residual_df["Demand_Range"] = pd.cut(
    residual_df["Actual"],
    bins=[0, 30000, 45000, 60000, np.inf],
    labels=[
        "Low (<30k)",
        "Medium (30k–45k)",
        "High (45k–60k)",
        "Very High (>60k)"
]
)

print(
    residual_df.groupby("Demand_Range", observed=False)["Residual"]
    .agg(["count", "mean", "std"])
)

                  count         mean          std
Demand_Range
Low (<30k)          170 -1915.274130  4337.072428
Medium (30k–45k)    267 -1646.737591  5724.641407
High (45k–60k)      239   852.864938  6376.064233
Very High (>60k)    150  4892.126459  6231.619364

In [122]:
df.groupby("ATM_ID")["Cash_Demand_Next_Day"].shift(1)

0           NaN
1       31478.0
2       41613.0
3       11316.0
4       34587.0
         ...
5653    60050.0
5654    17679.0
5655    51927.0
5656    30959.0
5657    49974.0
Name: Cash_Demand_Next_Day, Length: 5658, dtype: float64

In [126]:
daily = (
    df_clean
    .groupby(["ATM_ID", "Date"], as_index=False)
    .agg({
        "Cash_Demand_Next_Day": "mean",
        "Total_Withdrawals": "mean",
        "Total_Deposits": "mean"
    })
)

In [127]:
daily = daily.sort_values(["ATM_ID", "Date"]).reset_index(drop=True)

In [128]:
daily["Previous_Demand"] = (
    daily.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .shift(1)
)

daily["Previous_Withdrawals"] = (
    daily.groupby("ATM_ID")["Total_Withdrawals"]
    .shift(1)
)

daily["Previous_Deposits"] = (
    daily.groupby("ATM_ID")["Total_Deposits"]
    .shift(1)
)

In [129]:
daily["Rolling_Demand_3"] = (
    daily.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

daily["Rolling_Demand_7"] = (
    daily.groupby("ATM_ID")["Cash_Demand_Next_Day"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

In [130]:
print(daily.shape)
print(daily.columns.tolist())

print("\nMissing values:")
print(daily.isna().sum())

print("\nSample:")
display(daily.head(10))

(5223, 10)
['ATM_ID', 'Date', 'Cash_Demand_Next_Day', 'Total_Withdrawals', 'Total_Deposits', 'Previous_Demand', 'Previous_Withdrawals', 'Previous_Deposits', 'Rolling_Demand_3', 'Rolling_Demand_7']

Missing values:
ATM_ID                    0
Date                      0
Cash_Demand_Next_Day      0
Total_Withdrawals         0
Total_Deposits            0
Previous_Demand          50
Previous_Withdrawals     50
Previous_Deposits        50
Rolling_Demand_3        150
Rolling_Demand_7        350
dtype: int64

Sample:

,ATM_ID,Date,Cash_Demand_Next_Day,Total_Withdrawals,Total_Deposits,Previous_Demand,Previous_Withdrawals,Previous_Deposits,Rolling_Demand_3,Rolling_Demand_7
0,ATM_0001,2022-01-05,31478.0,37573.0,6224.0,NaN,NaN,NaN,NaN,NaN
1,ATM_0001,2022-01-13,41613.0,48156.0,10070.0,31478.0,37573.0,6224.0,NaN,NaN
2,ATM_0001,2022-01-20,11316.0,24671.0,13922.0,41613.0,48156.0,10070.0,NaN,NaN
3,ATM_0001,2022-01-28,34587.0,46383.0,12205.0,11316.0,24671.0,13922.0,28135.666667,NaN
4,ATM_0001,2022-02-01,23665.0,41972.0,18452.0,34587.0,46383.0,12205.0,29172.000000,NaN
5,ATM_0001,2022-02-24,40364.0,57436.0,13221.0,23665.0,41972.0,18452.0,23189.333333,NaN
6,ATM_0001,2022-02-27,38910.0,51743.0,4702.0,40364.0,57436.0,13221.0,32872.000000,NaN
7,ATM_0001,2022-03-05,63265.0,62626.5,10743.0,38910.0,51743.0,4702.0,34313.000000,31704.714286
8,ATM_0001,2022-03-08,63865.0,54368.0,8182.0,63265.0,62626.5,10743.0,47513.000000,36245.714286
9,ATM_0001,2022-03-17,28441.0,40466.0,11041.0,63865.0,54368.0,8182.0,55346.666667,39424.571429

In [131]:
# Features we want to test
historical_features = [
    "Previous_Demand",
    "Previous_Withdrawals",
    "Previous_Deposits",
    "Rolling_Demand_3",
    "Rolling_Demand_7"
]

# Check how much data is available
print(daily[historical_features].isna().sum())

Previous_Demand          50
Previous_Withdrawals     50
Previous_Deposits        50
Rolling_Demand_3        150
Rolling_Demand_7        350
dtype: int64

In [132]:
historical_features = [
    "Previous_Demand",
    "Previous_Withdrawals",
    "Previous_Deposits",
    "Rolling_Demand_3",
    "Rolling_Demand_7"
]

df_with_history = df_clean.merge(
    daily[["ATM_ID", "Date"] + historical_features],
    on=["ATM_ID", "Date"],
    how="left"
)

df_with_history.head()

,ATM_ID,Date,Day_of_Week,Time_of_Day,Total_Withdrawals,Total_Deposits,Location_Type,Holiday_Flag,Special_Event_Flag,Previous_Day_Cash_Level,...,Year,Month,Day,Day_of_Week_Num,Is_Weekend,Previous_Demand,Previous_Withdrawals,Previous_Deposits,Rolling_Demand_3,Rolling_Demand_7
0,ATM_0001,2022-01-05,Wednesday,Night,37573,6224,Standalone,0,1,109776,...,2022,1,5,2,0,NaN,NaN,NaN,NaN,NaN
1,ATM_0001,2022-01-13,Thursday,Morning,48156,10070,Gas Station,0,1,113068,...,2022,1,13,3,0,31478.0,37573.0,6224.0,NaN,NaN
2,ATM_0001,2022-01-20,Thursday,Evening,24671,13922,Mall,0,0,118171,...,2022,1,20,3,0,41613.0,48156.0,10070.0,NaN,NaN
3,ATM_0001,2022-01-28,Friday,Night,46383,12205,Mall,0,0,96931,...,2022,1,28,4,0,11316.0,24671.0,13922.0,28135.666667,NaN
4,ATM_0001,2022-02-01,Tuesday,Morning,41972,18452,Bank Branch,0,0,83257,...,2022,2,1,1,0,34587.0,46383.0,12205.0,29172.000000,NaN

In [133]:
print(df_with_history[historical_features].isna().sum())
print(df_with_history.shape)

Previous_Demand          55
Previous_Withdrawals     55
Previous_Deposits        55
Rolling_Demand_3        162
Rolling_Demand_7        371
dtype: int64
(5540, 24)

In [134]:
df_history_model = df_with_history.dropna(
    subset=historical_features
).copy()

print(df_history_model.shape)
print(df_history_model[historical_features].isna().sum())

(5169, 24)
Previous_Demand         0
Previous_Withdrawals    0
Previous_Deposits       0
Rolling_Demand_3        0
Rolling_Demand_7        0
dtype: int64

In [135]:
df_history_model["Year"] = df_history_model["Date"].dt.year
df_history_model["Month"] = df_history_model["Date"].dt.month
df_history_model["Day"] = df_history_model["Date"].dt.day
df_history_model["Day_of_Week_Num"] = df_history_model["Date"].dt.dayofweek
df_history_model["Is_Weekend"] = (
    df_history_model["Date"].dt.dayofweek >= 5
).astype(int)

categorical_cols = [
    "ATM_ID",
    "Time_of_Day",
    "Location_Type",
    "Weather_Condition"
]

df_history_model = pd.get_dummies(
    df_history_model,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

df_history_model = df_history_model.drop(
    columns=["Day_of_Week"]
)

print(df_history_model.shape)
print(df_history_model.dtypes.value_counts())

(5169, 78)
int64             67
float64            6
int32              4
datetime64[us]     1
Name: count, dtype: int64

In [136]:
train_h = df_history_model[
    df_history_model["Date"] < "2023-05-28"
].copy()

val_h = df_history_model[
    (df_history_model["Date"] >= "2023-05-28") &
    (df_history_model["Date"] < "2023-09-18")
].copy()

test_h = df_history_model[
    df_history_model["Date"] >= "2023-09-18"
].copy()

print("Train:", train_h.shape)
print("Validation:", val_h.shape)
print("Test:", test_h.shape)

print("\nDate ranges:")
print("Train:", train_h["Date"].min(), "→", train_h["Date"].max())
print("Val:", val_h["Date"].min(), "→", val_h["Date"].max())
print("Test:", test_h["Date"].min(), "→", test_h["Date"].max())

Train: (3505, 78)
Validation: (830, 78)
Test: (834, 78)

Date ranges:
Train: 2022-01-23 00:00:00 → 2023-05-27 00:00:00
Val: 2023-05-28 00:00:00 → 2023-09-17 00:00:00
Test: 2023-09-18 00:00:00 → 2024-01-01 00:00:00

In [138]:
target = "Cash_Demand_Next_Day"

X_train_h = train_h.drop(columns=[target, "Date"])
y_train_h = train_h[target]

X_val_h = val_h.drop(columns=[target, "Date"])
y_val_h = val_h[target]

X_test_h = test_h.drop(columns=[target, "Date"])
y_test_h = test_h[target]

print("X_train:", X_train_h.shape)
print("X_val:", X_val_h.shape)
print("X_test:", X_test_h.shape)

print("y_train:", y_train_h.shape)
print("y_val:", y_val_h.shape)
print("y_test:", y_test_h.shape)

X_train: (3505, 76)
X_val: (830, 76)
X_test: (834, 76)
y_train: (3505,)
y_val: (830,)
y_test: (834,)

In [139]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model_lr_h = LinearRegression()

model_lr_h.fit(X_train_h, y_train_h)

y_val_pred_h = model_lr_h.predict(X_val_h)

mae_h = mean_absolute_error(y_val_h, y_val_pred_h)
rmse_h = np.sqrt(mean_squared_error(y_val_h, y_val_pred_h))
r2_h = r2_score(y_val_h, y_val_pred_h)

print("Historical Features - Linear Regression")
print("MAE :", mae_h)
print("RMSE:", rmse_h)
print("R²  :", r2_h)

Historical Features - Linear Regression
MAE : 5284.772948323949
RMSE: 6296.553287173746
R²  : 0.8622245918266679

In [140]:
from sklearn.ensemble import RandomForestRegressor

model_rf_h = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)

model_rf_h.fit(X_train_h, y_train_h)

y_val_pred_rf_h = model_rf_h.predict(X_val_h)

mae_rf_h = mean_absolute_error(y_val_h, y_val_pred_rf_h)
rmse_rf_h = np.sqrt(mean_squared_error(y_val_h, y_val_pred_rf_h))
r2_rf_h = r2_score(y_val_h, y_val_pred_rf_h)

print("Historical Features - Random Forest")
print("MAE :", mae_rf_h)
print("RMSE:", rmse_rf_h)
print("R²  :", r2_rf_h)

Historical Features - Random Forest
MAE : 5401.810708785892
RMSE: 6497.058144953717
R²  : 0.853310358541636

In [142]:
four_features = [
    "Total_Withdrawals",
    "Total_Deposits",
    "Holiday_Flag",
    "Special_Event_Flag"
]

target = "Cash_Demand_Next_Day"

train_4 = df_clean[
    df_clean["Date"] < "2023-05-28"
].copy()

val_4 = df_clean[
    (df_clean["Date"] >= "2023-05-28") &
    (df_clean["Date"] < "2023-09-18")
].copy()

test_4 = df_clean[
    df_clean["Date"] >= "2023-09-18"
].copy()

X_train_4 = train_4[four_features]
y_train_4 = train_4[target]

X_val_4 = val_4[four_features]
y_val_4 = val_4[target]

X_test_4 = test_4[four_features]
y_test_4 = test_4[target]

print("Train:", X_train_4.shape)
print("Validation:", X_val_4.shape)
print("Test:", X_test_4.shape)
print("\nFeatures:", X_train_4.columns.tolist())

Train: (3876, 4)
Validation: (830, 4)
Test: (834, 4)

Features: ['Total_Withdrawals', 'Total_Deposits', 'Holiday_Flag', 'Special_Event_Flag']

In [143]:
model_lr_4 = LinearRegression()

model_lr_4.fit(X_train_4, y_train_4)

y_val_pred_4 = model_lr_4.predict(X_val_4)

mae_4 = mean_absolute_error(y_val_4, y_val_pred_4)
rmse_4 = np.sqrt(mean_squared_error(y_val_4, y_val_pred_4))
r2_4 = r2_score(y_val_4, y_val_pred_4)

print("4-Feature Linear Regression")
print("MAE :", mae_4)
print("RMSE:", rmse_4)
print("R²  :", r2_4)

4-Feature Linear Regression
MAE : 5194.604680880944
RMSE: 6201.083019259613
R²  : 0.8663709036829711

In [144]:
coefficients = pd.DataFrame({
    "Feature": X_train_4.columns,
    "Coefficient": model_lr_4.coef_
})

coefficients = coefficients.sort_values(
    "Coefficient",
    ascending=False
)

print(coefficients)

              Feature  Coefficient
3  Special_Event_Flag  7216.581381
2        Holiday_Flag  4814.783447
0   Total_Withdrawals     1.010547
1      Total_Deposits    -0.745769

In [145]:
print(df_clean[
    [
        "Total_Withdrawals",
        "Total_Deposits",
        "Holiday_Flag",
        "Special_Event_Flag",
        "Cash_Demand_Next_Day"
    ]
].corr()["Cash_Demand_Next_Day"].sort_values(ascending=False))

Cash_Demand_Next_Day    1.000000
Total_Withdrawals       0.895098
Special_Event_Flag      0.120361
Holiday_Flag            0.022340
Total_Deposits         -0.216192
Name: Cash_Demand_Next_Day, dtype: float64

In [146]:
X_train_w = train_4[["Total_Withdrawals"]]
X_val_w = val_4[["Total_Withdrawals"]]

model_w = LinearRegression()

model_w.fit(X_train_w, y_train_4)

y_val_pred_w = model_w.predict(X_val_w)

mae_w = mean_absolute_error(y_val_4, y_val_pred_w)
rmse_w = np.sqrt(mean_squared_error(y_val_4, y_val_pred_w))
r2_w = r2_score(y_val_4, y_val_pred_w)

print("Withdrawal-Only Linear Regression")
print("MAE :", mae_w)
print("RMSE:", rmse_w)
print("R²  :", r2_w)

Withdrawal-Only Linear Regression
MAE : 6203.681359839023
RMSE: 7637.163373690669
R²  : 0.7973110362625723

In [147]:
residuals_4 = y_val_4 - y_val_pred_4

error_analysis = pd.DataFrame({
    "Actual": y_val_4.values,
    "Predicted": y_val_pred_4,
    "Residual": residuals_4.values
})

def demand_group(x):
    if x < 30000:
        return "Low (<30k)"
    elif x < 45000:
        return "Medium (30k–45k)"
    elif x < 60000:
        return "High (45k–60k)"
    else:
        return "Very High (>60k)"

error_analysis["Demand_Group"] = error_analysis["Actual"].apply(demand_group)

print(
    error_analysis.groupby("Demand_Group")["Residual"]
    .agg(["count", "mean", "std"])
)

                  count         mean          std
Demand_Group
High (45k–60k)      239   808.536240  6399.085552
Low (<30k)          174 -1721.644969  4292.801741
Medium (30k–45k)    267 -1581.703885  5667.664586
Very High (>60k)    150  4838.024489  6123.495129

In [148]:
from sklearn.ensemble import GradientBoostingRegressor

model_gb_4 = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

model_gb_4.fit(X_train_4, y_train_4)

y_val_pred_gb_4 = model_gb_4.predict(X_val_4)

mae_gb_4 = mean_absolute_error(y_val_4, y_val_pred_gb_4)
rmse_gb_4 = np.sqrt(mean_squared_error(y_val_4, y_val_pred_gb_4))
r2_gb_4 = r2_score(y_val_4, y_val_pred_gb_4)

print("4-Feature Gradient Boosting")
print("MAE :", mae_gb_4)
print("RMSE:", rmse_gb_4)
print("R²  :", r2_gb_4)

4-Feature Gradient Boosting
MAE : 5263.83111001371
RMSE: 6287.901253682766
R²  : 0.8626029634238921

In [149]:
train_poly = train_4.copy()
val_poly = val_4.copy()

train_poly["Withdrawals_Squared"] = (
    train_poly["Total_Withdrawals"] ** 2
)

val_poly["Withdrawals_Squared"] = (
    val_poly["Total_Withdrawals"] ** 2
)

poly_features = [
    "Total_Withdrawals",
    "Total_Deposits",
    "Holiday_Flag",
    "Special_Event_Flag",
    "Withdrawals_Squared"
]

X_train_poly = train_poly[poly_features]
X_val_poly = val_poly[poly_features]

model_poly = LinearRegression()

model_poly.fit(X_train_poly, y_train_4)

y_val_pred_poly = model_poly.predict(X_val_poly)

mae_poly = mean_absolute_error(y_val_4, y_val_pred_poly)
rmse_poly = np.sqrt(mean_squared_error(y_val_4, y_val_pred_poly))
r2_poly = r2_score(y_val_4, y_val_pred_poly)

print("Polynomial Linear Regression")
print("MAE :", mae_poly)
print("RMSE:", rmse_poly)
print("R²  :", r2_poly)

Polynomial Linear Regression
MAE : 5448.732048130596
RMSE: 6635.491350156208
R²  : 0.8469927129252484

In [150]:
# Simple transaction-only model

transaction_features = [
    "Total_Withdrawals",
    "Total_Deposits"
]

X_train_tx = train_4[transaction_features]
X_val_tx = val_4[transaction_features]

model_tx = LinearRegression()

model_tx.fit(X_train_tx, y_train_4)

y_val_pred_tx = model_tx.predict(X_val_tx)

mae_tx = mean_absolute_error(y_val_4, y_val_pred_tx)
rmse_tx = np.sqrt(mean_squared_error(y_val_4, y_val_pred_tx))
r2_tx = r2_score(y_val_4, y_val_pred_tx)

print("Transaction-Only Linear Regression")
print("MAE :", mae_tx)
print("RMSE:", rmse_tx)
print("R²  :", r2_tx)

print("\nCoefficients:")
print(pd.DataFrame({
    "Feature": transaction_features,
    "Coefficient": model_tx.coef_
}))

print("\nIntercept:", model_tx.intercept_)

Transaction-Only Linear Regression
MAE : 5445.629765746565
RMSE: 6639.384650644272
R²  : 0.8468131096147637

Coefficients:
             Feature  Coefficient
0  Total_Withdrawals     1.006094
1     Total_Deposits    -0.733731

Intercept: 394.5717079904207

In [151]:
def predict_cash_demand(
    withdrawals,
    deposits,
    holiday,
    special_event
):
    input_data = pd.DataFrame({
        "Total_Withdrawals": [withdrawals],
        "Total_Deposits": [deposits],
        "Holiday_Flag": [holiday],
        "Special_Event_Flag": [special_event]
    })

    prediction = model_lr_4.predict(input_data)[0]

    return prediction


prediction = predict_cash_demand(
    withdrawals=58000,
    deposits=9000,
    holiday=0,
    special_event=1
)

print("Predicted next-day cash demand:", prediction)

Predicted next-day cash demand: 58620.5387895967

In [152]:
print(
    df_clean[
        [
            "Previous_Day_Cash_Level",
            "Cash_Demand_Next_Day"
        ]
    ].describe()
)

       Previous_Day_Cash_Level  Cash_Demand_Next_Day
count              5540.000000           5540.000000
mean             100345.400542          43079.951986
std               20106.364598          16821.716778
min               23266.000000              0.000000
25%               86568.500000          31576.750000
50%              100308.500000          42544.000000
75%              113979.500000          53879.000000
max              172227.000000         114724.000000

In [153]:
df_risk = df_clean[
    [
        "Previous_Day_Cash_Level",
        "Cash_Demand_Next_Day"
    ]
].copy()

df_risk["Cash_Coverage"] = (
    df_risk["Previous_Day_Cash_Level"] /
    df_risk["Cash_Demand_Next_Day"].replace(0, np.nan)
)

print(df_risk["Cash_Coverage"].describe())

count    5518.000000
mean        3.393269
std        29.030244
min         0.354995
25%         1.769601
50%         2.344601
75%         3.223309
max      2124.738095
Name: Cash_Coverage, dtype: float64

In [154]:
coverage = df_risk["Cash_Coverage"]

print("Coverage < 1.0:", (coverage < 1.0).sum())
print("Coverage < 1.25:", (coverage < 1.25).sum())
print("Coverage < 1.50:", (coverage < 1.50).sum())
print("Coverage >= 1.50:", (coverage >= 1.50).sum())

print("\nPercentages:")
print("Coverage < 1.0 :", (coverage < 1.0).mean() * 100, "%")
print("Coverage < 1.25:", (coverage < 1.25).mean() * 100, "%")
print("Coverage < 1.50:", (coverage < 1.50).mean() * 100, "%")

Coverage < 1.0: 86
Coverage < 1.25: 325
Coverage < 1.50: 735
Coverage >= 1.50: 4783

Percentages:
Coverage < 1.0 : 1.552346570397112 %
Coverage < 1.25: 5.866425992779783 %
Coverage < 1.50: 13.267148014440433 %

In [155]:
print(
    df_clean[
        [
            "Date",
            "Previous_Day_Cash_Level",
            "Cash_Demand_Next_Day"
        ]
    ].sort_values("Date").head(20)
)

           Date  Previous_Day_Cash_Level  Cash_Demand_Next_Day
4722 2022-01-01                    87830                 40733
4619 2022-01-01                   111591                 42094
1919 2022-01-01                   120901                 40441
237  2022-01-01                    60709                 20161
4050 2022-01-01                   110512                 46376
4049 2022-01-01                    65170                 41375
1258 2022-01-01                   135797                 29921
793  2022-01-01                    79111                 35801
1376 2022-01-02                    87693                 66387
5099 2022-01-02                    90724                 32322
1149 2022-01-02                   100043                 38394
668  2022-01-02                    91814                 41120
3818 2022-01-02                   144265                 13124
669  2022-01-02                    81515                 46418
670  2022-01-02                    99582                 44598
2727 2022-01-03                   137935                 28914
2834 2022-01-03                    96790                 58356
4051 2022-01-03                    96786                 46406
4052 2022-01-03                    93022                 45348
4519 2022-01-03                    72969                 80392

In [156]:
cash_variation = (
    df_clean
    .groupby(["ATM_ID", "Date"])["Previous_Day_Cash_Level"]
    .nunique()
)

print("ATM-days with multiple cash levels:",
      (cash_variation > 1).sum())

print("Total unique ATM-days:",
      len(cash_variation))

ATM-days with multiple cash levels: 308
Total unique ATM-days: 5223

In [157]:
cash_variation_counts = (
    df_clean
    .groupby(["ATM_ID", "Date"])["Previous_Day_Cash_Level"]
    .nunique()
)

print(cash_variation_counts[cash_variation_counts > 1].describe())

print(
    "ATM-days with 2 cash levels:",
    (cash_variation_counts == 2).sum()
)

print(
    "ATM-days with 3+ cash levels:",
    (cash_variation_counts >= 3).sum()
)

count    308.000000
mean       2.029221
std        0.187013
min        2.000000
25%        2.000000
50%        2.000000
75%        2.000000
max        4.000000
Name: Previous_Day_Cash_Level, dtype: float64
ATM-days with 2 cash levels: 300
ATM-days with 3+ cash levels: 8

In [158]:
multi_cash_days = (
    df_clean
    .groupby(["ATM_ID", "Date"])["Previous_Day_Cash_Level"]
    .nunique()
)

multi_cash_days = multi_cash_days[multi_cash_days > 1]

problem_rows = df_clean.set_index(["ATM_ID", "Date"]).loc[
    multi_cash_days.index
].reset_index()

print(
    problem_rows[
        ["ATM_ID", "Date", "Time_of_Day", "Previous_Day_Cash_Level"]
    ].sort_values(["ATM_ID", "Date"]).head(30)
)

      ATM_ID       Date Time_of_Day  Previous_Day_Cash_Level
0   ATM_0001 2022-03-05   Afternoon                    47915
1   ATM_0001 2022-03-05     Morning                   110780
2   ATM_0001 2022-05-27     Evening                    95065
3   ATM_0001 2022-05-27     Morning                   112470
4   ATM_0001 2022-07-28     Morning                    83011
5   ATM_0001 2022-07-28   Afternoon                   110282
6   ATM_0001 2022-10-16     Evening                   108793
7   ATM_0001 2022-10-16   Afternoon                    74836
8   ATM_0001 2022-11-06     Morning                    56746
9   ATM_0001 2022-11-06       Night                   116095
10  ATM_0001 2022-11-23     Morning                   125488
11  ATM_0001 2022-11-23       Night                    99967
12  ATM_0001 2022-11-30     Morning                    88325
13  ATM_0001 2022-11-30     Evening                    80690
14  ATM_0001 2023-07-03     Evening                   108242
15  ATM_0001 2023-07-03       Night                    73939
16  ATM_0002 2022-02-03     Evening                   119557
17  ATM_0002 2022-02-03     Morning                    88195
18  ATM_0002 2022-05-24     Morning                    69404
19  ATM_0002 2022-05-24       Night                    94477
20  ATM_0002 2022-09-17   Afternoon                    90060
21  ATM_0002 2022-09-17     Evening                    77321
22  ATM_0002 2022-12-19   Afternoon                   129772
23  ATM_0002 2022-12-19       Night                    51595
24  ATM_0002 2023-03-27     Morning                    97930
25  ATM_0002 2023-03-27   Afternoon                    76350
26  ATM_0002 2023-05-10     Morning                   115869
27  ATM_0002 2023-05-10   Afternoon                    86222
28  ATM_0002 2023-07-07     Morning                   110288
29  ATM_0002 2023-07-07     Evening                   115068

In [159]:
# Create validation error analysis
error_analysis = pd.DataFrame({
    "Actual": y_val_4.values,
    "Predicted": y_val_pred_4
})

# Create demand ranges
def demand_range(x):
    if x < 30000:
        return "Low (<30k)"
    elif x < 45000:
        return "Medium (30k–45k)"
    elif x < 60000:
        return "High (45k–60k)"
    else:
        return "Very High (>60k)"

error_analysis["Demand_Range"] = error_analysis["Actual"].apply(demand_range)

# Calculate metrics for each range
range_results = (
    error_analysis
    .groupby("Demand_Range")
    .apply(lambda g: pd.Series({
        "Samples": len(g),
        "MAE": np.mean(np.abs(g["Actual"] - g["Predicted"])),
        "RMSE": np.sqrt(np.mean((g["Actual"] - g["Predicted"]) ** 2)),
        "Mean_Error": np.mean(g["Predicted"] - g["Actual"])
    }))
)

print(range_results)

                  Samples          MAE         RMSE   Mean_Error
Demand_Range
High (45k–60k)      239.0  5578.231595  6436.668002  -808.536240
Low (<30k)          174.0  3745.375918  4613.707760  1721.644969
Medium (30k–45k)    267.0  4888.714738  5874.002072  1581.703885
Very High (>60k)    150.0  6808.948594  7788.048040 -4838.024489

In [160]:
error_analysis["Absolute_Percentage_Error"] = (
    np.abs(error_analysis["Actual"] - error_analysis["Predicted"])
    / error_analysis["Actual"].replace(0, np.nan)
) * 100

# Overall MAPE, ignoring zero-demand rows
mape = error_analysis["Absolute_Percentage_Error"].mean()

print(f"MAPE (excluding zero-demand rows): {mape:.2f}%")
print(f"Approx. percentage accuracy: {100 - mape:.2f}%")| ---------------- | ------: | -----: | -----: | ------: |
| Low (<30k)       |     174 | ₹3,745 | ₹4,614 | +₹1,722 |
| Medium (30–45k)  |     267 | ₹4,889 | ₹5,874 | +₹1,582 |
| High (45–60k)    |     239 | ₹5,578 | ₹6,437 |   −₹809 |
| Very High (>60k) |     150 | ₹6,809 | ₹7,788 | −₹4,838 |
# Calculate absolute percentage error

MAPE (excluding zero-demand rows): 15.92%
Approx. percentage accuracy: 84.08%